OPTIONS (SKIP=1)
LOAD DATA
APPEND INTO TABLE "ODBCAPTURE"."TYPE_PATH"
FIELDS CSV WITH EMBEDDED
TRAILING NULLCOLS
   (PARENT_TYPE_SEQ                FLOAT EXTERNAL
   ,TYPE_SEQ                       FLOAT EXTERNAL
   )
