OPTIONS (SKIP=1)
LOAD DATA
APPEND INTO TABLE "ODBCAPTURE"."TYPE_CONF"
FIELDS CSV WITH EMBEDDED
TRAILING NULLCOLS
   (TYPE_SEQ                       FLOAT EXTERNAL
   ,INSTALL_TYPE                   CHAR(10)
   ,NOTES                          CHAR(1024)
   )
