
select '=== CLUE create_grnt ===' as SCRIPT_NAME from dual;

-- Script File "create_grnt"
--    Create grants and audits on objects

   -- Application: Clue Notes For Oracle
   -- Generated by DTGen (http://dmstex.com/services/dtgen)
   -- December  16, 2013  11:32:36 AM

   --
   --
   -- © Duane.Dieterich@DMSTEX.com 2013
   --
   -- All Rights Reserved
   --
   -- No part of this software may be reproduced, copied, modified or adapted,
   -- without the prior written consent of the author, unless otherwise
   -- indicated for stand-alone materials.
   --
   -- You may quote extracts from this software with attribution to
   -- Duane.Dieterich@DMSTEX.com
   --
   -- For any other mode of sharing, please contact Duane.Dieterich@DMSTEX.com.
   --
   -- Commercial use and distribution of this software is not allowed without
   -- express and prior written consent of the author.
   --
   -- THE SOFTWARE IS PROVIDED "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES,
   -- INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY
   -- AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL
   -- THE COPYRIGHT HOLDER OR DMSTEX BUSINESS SOLUTIONS LLC, ITS MEMBERS,
   -- MANAGERS, OR EMPLOYEES BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
   -- SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED
   -- TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
   -- PROFITS; CORRUPTION OF DATA, OR BUSINESS INTERRUPTION) HOWEVER CAUSED
   -- AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
   -- OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF
   -- THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH
   -- DAMAGE.
   --
   --



--  Dispositions_DOBJ grants
grant execute on Dispositions_DOBJ to CLUE_app
/

--  Dispositions_DOM grants
grant execute on Dispositions_DOM to CLUE_app
/

--  Dispositions_DTAB grants
grant execute on Dispositions_DTAB to CLUE_app
/

--  Flagged_DOBJ grants
grant execute on Flagged_DOBJ to CLUE_app
/

--  Flagged_DOM grants
grant execute on Flagged_DOM to CLUE_app
/

--  Flagged_DTAB grants
grant execute on Flagged_DTAB to CLUE_app
/

--  Resolutions_DOBJ grants
grant execute on Resolutions_DOBJ to CLUE_app
/

--  Resolutions_DOM grants
grant execute on Resolutions_DOM to CLUE_app
/

--  Resolutions_DTAB grants
grant execute on Resolutions_DTAB to CLUE_app
/

--  UTIL grants
grant execute on UTIL to CLUE_app
/

--  UTIL_LOG grants
grant delete on UTIL_LOG to CLUE_adm
/
grant insert on UTIL_LOG to CLUE_app
/
grant select on UTIL_LOG to CLUE_app
/

--  UTIL_NVP grants
grant delete on UTIL_NVP to CLUE_adm
/
grant insert on UTIL_NVP to CLUE_adm
/
grant select on UTIL_NVP to CLUE_app
/
grant update on UTIL_NVP to CLUE_adm
/

--  UTIL_TRC grants
grant delete on UTIL_TRC to CLUE_app
/
grant insert on UTIL_TRC to CLUE_app
/
grant select on UTIL_TRC to CLUE_app
/
grant update on UTIL_TRC to CLUE_app
/

--  accusation grants
grant delete on accusation to CLUE_app
/
grant insert on accusation to CLUE_app
/
grant select on accusation to CLUE_app
/
grant update on accusation to CLUE_app
/

--  accusation_ACT grants
grant delete on accusation_ACT to CLUE_app
/
grant insert on accusation_ACT to CLUE_app
/
grant select on accusation_ACT to CLUE_app
/
grant update on accusation_ACT to CLUE_app
/

--  accusation_DML grants
grant execute on accusation_DML to CLUE_app
/

--  accusation_VOBJ grants
grant execute on accusation_VOBJ to CLUE_app
/

--  accusation_VTAB grants
grant execute on accusation_VTAB to CLUE_app
/

--  action_cards grants
grant delete on action_cards to CLUE_app
/
grant insert on action_cards to CLUE_app
/
grant select on action_cards to CLUE_app
/
grant update on action_cards to CLUE_app
/

--  action_cards_ACT grants
grant delete on action_cards_ACT to CLUE_app
/
grant insert on action_cards_ACT to CLUE_app
/
grant select on action_cards_ACT to CLUE_app
/
grant update on action_cards_ACT to CLUE_app
/

--  action_cards_DML grants
grant execute on action_cards_DML to CLUE_app
/

--  action_cards_SEQ grants
grant alter on action_cards_SEQ to CLUE_adm
/
grant select on action_cards_SEQ to CLUE_app
/

--  action_cards_VOBJ grants
grant execute on action_cards_VOBJ to CLUE_app
/

--  action_cards_VTAB grants
grant execute on action_cards_VTAB to CLUE_app
/

--  actions grants
grant delete on actions to CLUE_app
/
grant insert on actions to CLUE_app
/
grant select on actions to CLUE_app
/
grant update on actions to CLUE_app
/

--  actions_A grants
grant select on actions_A to CLUE_app
/

--  actions_ACT grants
grant delete on actions_ACT to CLUE_app
/
grant insert on actions_ACT to CLUE_app
/
grant select on actions_ACT to CLUE_app
/
grant update on actions_ACT to CLUE_app
/

--  actions_DML grants
grant execute on actions_DML to CLUE_app
/

--  actions_SEQ grants
grant alter on actions_SEQ to CLUE_adm
/
grant select on actions_SEQ to CLUE_app
/

--  actions_VOBJ grants
grant execute on actions_VOBJ to CLUE_app
/

--  actions_VTAB grants
grant execute on actions_VTAB to CLUE_app
/

--  card_types grants
grant delete on card_types to CLUE_app
/
grant insert on card_types to CLUE_app
/
grant select on card_types to CLUE_app
/
grant update on card_types to CLUE_app
/

--  card_types_ACT grants
grant delete on card_types_ACT to CLUE_app
/
grant insert on card_types_ACT to CLUE_app
/
grant select on card_types_ACT to CLUE_app
/
grant update on card_types_ACT to CLUE_app
/

--  card_types_DML grants
grant execute on card_types_DML to CLUE_app
/

--  card_types_SEQ grants
grant alter on card_types_SEQ to CLUE_adm
/
grant select on card_types_SEQ to CLUE_app
/

--  card_types_VOBJ grants
grant execute on card_types_VOBJ to CLUE_app
/

--  card_types_VTAB grants
grant execute on card_types_VTAB to CLUE_app
/

--  cards grants
grant delete on cards to CLUE_app
/
grant insert on cards to CLUE_app
/
grant select on cards to CLUE_app
/
grant update on cards to CLUE_app
/

--  cards_ACT grants
grant delete on cards_ACT to CLUE_app
/
grant insert on cards_ACT to CLUE_app
/
grant select on cards_ACT to CLUE_app
/
grant update on cards_ACT to CLUE_app
/

--  cards_DML grants
grant execute on cards_DML to CLUE_app
/

--  cards_SEQ grants
grant alter on cards_SEQ to CLUE_adm
/
grant select on cards_SEQ to CLUE_app
/

--  cards_VOBJ grants
grant execute on cards_VOBJ to CLUE_app
/

--  cards_VTAB grants
grant execute on cards_VTAB to CLUE_app
/

--  clue grants
grant execute on clue to CLUE_app
/

--  games grants
grant delete on games to CLUE_app
/
grant insert on games to CLUE_app
/
grant select on games to CLUE_app
/
grant update on games to CLUE_app
/

--  games_ACT grants
grant delete on games_ACT to CLUE_app
/
grant insert on games_ACT to CLUE_app
/
grant select on games_ACT to CLUE_app
/
grant update on games_ACT to CLUE_app
/

--  games_DML grants
grant execute on games_DML to CLUE_app
/

--  games_SEQ grants
grant alter on games_SEQ to CLUE_adm
/
grant select on games_SEQ to CLUE_app
/

--  games_VOBJ grants
grant execute on games_VOBJ to CLUE_app
/

--  games_VTAB grants
grant execute on games_VTAB to CLUE_app
/

--  pcard_actions grants
grant delete on pcard_actions to CLUE_app
/
grant insert on pcard_actions to CLUE_app
/
grant select on pcard_actions to CLUE_app
/
grant update on pcard_actions to CLUE_app
/

--  pcard_actions_ACT grants
grant delete on pcard_actions_ACT to CLUE_app
/
grant insert on pcard_actions_ACT to CLUE_app
/
grant select on pcard_actions_ACT to CLUE_app
/
grant update on pcard_actions_ACT to CLUE_app
/

--  pcard_actions_DML grants
grant execute on pcard_actions_DML to CLUE_app
/

--  pcard_actions_SEQ grants
grant alter on pcard_actions_SEQ to CLUE_adm
/
grant select on pcard_actions_SEQ to CLUE_app
/

--  pcard_actions_VOBJ grants
grant execute on pcard_actions_VOBJ to CLUE_app
/

--  pcard_actions_VTAB grants
grant execute on pcard_actions_VTAB to CLUE_app
/

--  players grants
grant delete on players to CLUE_app
/
grant insert on players to CLUE_app
/
grant select on players to CLUE_app
/
grant update on players to CLUE_app
/

--  players_ACT grants
grant delete on players_ACT to CLUE_app
/
grant insert on players_ACT to CLUE_app
/
grant select on players_ACT to CLUE_app
/
grant update on players_ACT to CLUE_app
/

--  players_DML grants
grant execute on players_DML to CLUE_app
/

--  players_SEQ grants
grant alter on players_SEQ to CLUE_adm
/
grant select on players_SEQ to CLUE_app
/

--  players_VOBJ grants
grant execute on players_VOBJ to CLUE_app
/

--  players_VTAB grants
grant execute on players_VTAB to CLUE_app
/

--  revelation grants
grant delete on revelation to CLUE_app
/
grant insert on revelation to CLUE_app
/
grant select on revelation to CLUE_app
/
grant update on revelation to CLUE_app
/

--  revelation_ACT grants
grant delete on revelation_ACT to CLUE_app
/
grant insert on revelation_ACT to CLUE_app
/
grant select on revelation_ACT to CLUE_app
/
grant update on revelation_ACT to CLUE_app
/

--  revelation_DML grants
grant execute on revelation_DML to CLUE_app
/

--  revelation_VOBJ grants
grant execute on revelation_VOBJ to CLUE_app
/

--  revelation_VTAB grants
grant execute on revelation_VTAB to CLUE_app
/

--  suggestion grants
grant delete on suggestion to CLUE_app
/
grant insert on suggestion to CLUE_app
/
grant select on suggestion to CLUE_app
/
grant update on suggestion to CLUE_app
/

--  suggestion_ACT grants
grant delete on suggestion_ACT to CLUE_app
/
grant insert on suggestion_ACT to CLUE_app
/
grant select on suggestion_ACT to CLUE_app
/
grant update on suggestion_ACT to CLUE_app
/

--  suggestion_DML grants
grant execute on suggestion_DML to CLUE_app
/

--  suggestion_VOBJ grants
grant execute on suggestion_VOBJ to CLUE_app
/

--  suggestion_VTAB grants
grant execute on suggestion_VTAB to CLUE_app
/

--  users grants
grant delete on users to CLUE_app
/
grant insert on users to CLUE_app
/
grant select on users to CLUE_app
/
grant update on users to CLUE_app
/

--  users_ACT grants
grant delete on users_ACT to CLUE_app
/
grant insert on users_ACT to CLUE_app
/
grant select on users_ACT to CLUE_app
/
grant update on users_ACT to CLUE_app
/

--  users_DML grants
grant execute on users_DML to CLUE_app
/

--  users_SEQ grants
grant alter on users_SEQ to CLUE_adm
/
grant select on users_SEQ to CLUE_app
/

--  users_VOBJ grants
grant execute on users_VOBJ to CLUE_app
/

--  users_VTAB grants
grant execute on users_VTAB to CLUE_app
/

