
select '=== CLUE create_usyn ===' as SCRIPT_NAME from dual;

-- Script File "create_usyn"
--    Create user synonyms

   -- Application: Clue Notes For Oracle
   -- Generated by DTGen (http://dmstex.com/services/dtgen)
   -- December  16, 2013  11:32:36 AM

   --
   --
   -- © Duane.Dieterich@DMSTEX.com 2013
   --
   -- All Rights Reserved
   --
   -- No part of this software may be reproduced, copied, modified or adapted,
   -- without the prior written consent of the author, unless otherwise
   -- indicated for stand-alone materials.
   --
   -- You may quote extracts from this software with attribution to
   -- Duane.Dieterich@DMSTEX.com
   --
   -- For any other mode of sharing, please contact Duane.Dieterich@DMSTEX.com.
   --
   -- Commercial use and distribution of this software is not allowed without
   -- express and prior written consent of the author.
   --
   -- THE SOFTWARE IS PROVIDED "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES,
   -- INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY
   -- AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL
   -- THE COPYRIGHT HOLDER OR DMSTEX BUSINESS SOLUTIONS LLC, ITS MEMBERS,
   -- MANAGERS, OR EMPLOYEES BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
   -- SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED
   -- TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
   -- PROFITS; CORRUPTION OF DATA, OR BUSINESS INTERRUPTION) HOWEVER CAUSED
   -- AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
   -- OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF
   -- THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH
   -- DAMAGE.
   --
   --



create synonym Dispositions_DOBJ for CLUE.Dispositions_DOBJ
/
create synonym Dispositions_DOM for CLUE.Dispositions_DOM
/
create synonym Dispositions_DTAB for CLUE.Dispositions_DTAB
/
create synonym Flagged_DOBJ for CLUE.Flagged_DOBJ
/
create synonym Flagged_DOM for CLUE.Flagged_DOM
/
create synonym Flagged_DTAB for CLUE.Flagged_DTAB
/
create synonym Resolutions_DOBJ for CLUE.Resolutions_DOBJ
/
create synonym Resolutions_DOM for CLUE.Resolutions_DOM
/
create synonym Resolutions_DTAB for CLUE.Resolutions_DTAB
/
create synonym UTIL for CLUE.UTIL
/
create synonym UTIL_LOG for CLUE.UTIL_LOG
/
create synonym UTIL_NVP for CLUE.UTIL_NVP
/
create synonym UTIL_TRC for CLUE.UTIL_TRC
/
create synonym accusation for CLUE.accusation
/
create synonym accusation_ACT for CLUE.accusation_ACT
/
create synonym accusation_DML for CLUE.accusation_DML
/
create synonym accusation_VOBJ for CLUE.accusation_VOBJ
/
create synonym accusation_VTAB for CLUE.accusation_VTAB
/
create synonym action_cards for CLUE.action_cards
/
create synonym action_cards_ACT for CLUE.action_cards_ACT
/
create synonym action_cards_DML for CLUE.action_cards_DML
/
create synonym action_cards_SEQ for CLUE.action_cards_SEQ
/
create synonym action_cards_VOBJ for CLUE.action_cards_VOBJ
/
create synonym action_cards_VTAB for CLUE.action_cards_VTAB
/
create synonym actions for CLUE.actions
/
create synonym actions_A for CLUE.actions_A
/
create synonym actions_ACT for CLUE.actions_ACT
/
create synonym actions_DML for CLUE.actions_DML
/
create synonym actions_SEQ for CLUE.actions_SEQ
/
create synonym actions_VOBJ for CLUE.actions_VOBJ
/
create synonym actions_VTAB for CLUE.actions_VTAB
/
create synonym card_types for CLUE.card_types
/
create synonym card_types_ACT for CLUE.card_types_ACT
/
create synonym card_types_DML for CLUE.card_types_DML
/
create synonym card_types_SEQ for CLUE.card_types_SEQ
/
create synonym card_types_VOBJ for CLUE.card_types_VOBJ
/
create synonym card_types_VTAB for CLUE.card_types_VTAB
/
create synonym cards for CLUE.cards
/
create synonym cards_ACT for CLUE.cards_ACT
/
create synonym cards_DML for CLUE.cards_DML
/
create synonym cards_SEQ for CLUE.cards_SEQ
/
create synonym cards_VOBJ for CLUE.cards_VOBJ
/
create synonym cards_VTAB for CLUE.cards_VTAB
/
create synonym clue for CLUE.clue
/
create synonym games for CLUE.games
/
create synonym games_ACT for CLUE.games_ACT
/
create synonym games_DML for CLUE.games_DML
/
create synonym games_SEQ for CLUE.games_SEQ
/
create synonym games_VOBJ for CLUE.games_VOBJ
/
create synonym games_VTAB for CLUE.games_VTAB
/
create synonym pcard_actions for CLUE.pcard_actions
/
create synonym pcard_actions_ACT for CLUE.pcard_actions_ACT
/
create synonym pcard_actions_DML for CLUE.pcard_actions_DML
/
create synonym pcard_actions_SEQ for CLUE.pcard_actions_SEQ
/
create synonym pcard_actions_VOBJ for CLUE.pcard_actions_VOBJ
/
create synonym pcard_actions_VTAB for CLUE.pcard_actions_VTAB
/
create synonym players for CLUE.players
/
create synonym players_ACT for CLUE.players_ACT
/
create synonym players_DML for CLUE.players_DML
/
create synonym players_SEQ for CLUE.players_SEQ
/
create synonym players_VOBJ for CLUE.players_VOBJ
/
create synonym players_VTAB for CLUE.players_VTAB
/
create synonym revelation for CLUE.revelation
/
create synonym revelation_ACT for CLUE.revelation_ACT
/
create synonym revelation_DML for CLUE.revelation_DML
/
create synonym revelation_VOBJ for CLUE.revelation_VOBJ
/
create synonym revelation_VTAB for CLUE.revelation_VTAB
/
create synonym suggestion for CLUE.suggestion
/
create synonym suggestion_ACT for CLUE.suggestion_ACT
/
create synonym suggestion_DML for CLUE.suggestion_DML
/
create synonym suggestion_VOBJ for CLUE.suggestion_VOBJ
/
create synonym suggestion_VTAB for CLUE.suggestion_VTAB
/
create synonym users for CLUE.users
/
create synonym users_ACT for CLUE.users_ACT
/
create synonym users_DML for CLUE.users_DML
/
create synonym users_SEQ for CLUE.users_SEQ
/
create synonym users_VOBJ for CLUE.users_VOBJ
/
create synonym users_VTAB for CLUE.users_VTAB
/
