
select '=== CLUE create_dom ===' as SCRIPT_NAME from dual;

-- Script File "create_dom"
--    Create Descrete Domains

   -- Application: Clue Notes For Oracle
   -- Generated by DTGen (http://dmstex.com/services/dtgen)
   -- December  16, 2013  11:32:29 AM

   --
   --
   -- © Duane.Dieterich@DMSTEX.com 2013
   --
   -- All Rights Reserved
   --
   -- No part of this software may be reproduced, copied, modified or adapted,
   -- without the prior written consent of the author, unless otherwise
   -- indicated for stand-alone materials.
   --
   -- You may quote extracts from this software with attribution to
   -- Duane.Dieterich@DMSTEX.com
   --
   -- For any other mode of sharing, please contact Duane.Dieterich@DMSTEX.com.
   --
   -- Commercial use and distribution of this software is not allowed without
   -- express and prior written consent of the author.
   --
   -- THE SOFTWARE IS PROVIDED "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES,
   -- INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY
   -- AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL
   -- THE COPYRIGHT HOLDER OR DMSTEX BUSINESS SOLUTIONS LLC, ITS MEMBERS,
   -- MANAGERS, OR EMPLOYEES BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
   -- SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED
   -- TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
   -- PROFITS; CORRUPTION OF DATA, OR BUSINESS INTERRUPTION) HOWEVER CAUSED
   -- AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
   -- OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF
   -- THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH
   -- DAMAGE.
   --
   --



CREATE type Dispositions_dobj
is
   -- Dispositions Domain Value Record Type
object
   (value        varchar2(4)
   ,seq          number
   ,description  varchar2(1000)
   )
/
select 'DISPOSITIONS_DOBJ' as "Type:"
 from  user_errors
 where name  = 'DISPOSITIONS_DOBJ'
  and  type  = 'TYPE'
  and  rownum = 1
/
select '('||line||'/'||position||') '||text as error
 from  user_errors
 where name = 'DISPOSITIONS_DOBJ'
  and  type = 'TYPE'
 order by sequence
/

CREATE type Dispositions_dtab
is
   -- Dispositions Domain Value Table Type
table of Dispositions_dobj
/
select 'DISPOSITIONS_DTAB' as "Type:"
 from  user_errors
 where name  = 'DISPOSITIONS_DTAB'
  and  type  = 'TYPE'
  and  rownum = 1
/
select '('||line||'/'||position||') '||text as error
 from  user_errors
 where name = 'DISPOSITIONS_DTAB'
  and  type = 'TYPE'
 order by sequence
/

CREATE package Dispositions_dom
is

   -- Package Dispositions_Dom
   --    Domains and Domain Values

   -- Application: Clue Notes For Oracle
   -- Generated by DTGen (http://dmstex.com/services/dtgen)
   -- December  16, 2013  11:32:29 AM

   --
   --
   -- © Duane.Dieterich@DMSTEX.com 2013
   --
   -- All Rights Reserved
   --
   -- No part of this software may be reproduced, copied, modified or adapted,
   -- without the prior written consent of the author, unless otherwise
   -- indicated for stand-alone materials.
   --
   -- You may quote extracts from this software with attribution to
   -- Duane.Dieterich@DMSTEX.com
   --
   -- For any other mode of sharing, please contact Duane.Dieterich@DMSTEX.com.
   --
   -- Commercial use and distribution of this software is not allowed without
   -- express and prior written consent of the author.
   --
   -- THE SOFTWARE IS PROVIDED "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES,
   -- INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY
   -- AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL
   -- THE COPYRIGHT HOLDER OR DMSTEX BUSINESS SOLUTIONS LLC, ITS MEMBERS,
   -- MANAGERS, OR EMPLOYEES BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
   -- SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED
   -- TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
   -- PROFITS; CORRUPTION OF DATA, OR BUSINESS INTERRUPTION) HOWEVER CAUSED
   -- AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
   -- OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF
   -- THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH
   -- DAMAGE.
   --
   --


   -- An instance of the Table Type
   tab  Dispositions_dtab;

   -- Domain Description
   function describe
      return varchar2;

   -- Domain Values Functions
   function get_seq
         (value_in  in  varchar2)
      return number;
   function get_desc
         (value_in  in  varchar2)
      return varchar2;
   function includes
         (value_in  in  varchar2)
      return boolean;
   -- select * from table(dispositions_dom.table_recs);
   function table_recs
      return Dispositions_dtab;

end Dispositions_dom;
/
select 'DISPOSITIONS_DOM' as "Package:"
 from  user_errors
 where name  = 'DISPOSITIONS_DOM'
  and  type  = 'PACKAGE'
  and  rownum = 1
/
select '('||line||'/'||position||') '||text as error
 from  user_errors
 where name = 'DISPOSITIONS_DOM'
  and  type = 'PACKAGE'
 order by sequence
/

CREATE package body Dispositions_dom
is

   -- Package Body Dispositions_Dom
   --    Domains and Domain Values

   -- Application: Clue Notes For Oracle
   -- Generated by DTGen (http://dmstex.com/services/dtgen)
   -- December  16, 2013  11:32:29 AM

   --
   --
   -- © Duane.Dieterich@DMSTEX.com 2013
   --
   -- All Rights Reserved
   --
   -- No part of this software may be reproduced, copied, modified or adapted,
   -- without the prior written consent of the author, unless otherwise
   -- indicated for stand-alone materials.
   --
   -- You may quote extracts from this software with attribution to
   -- Duane.Dieterich@DMSTEX.com
   --
   -- For any other mode of sharing, please contact Duane.Dieterich@DMSTEX.com.
   --
   -- Commercial use and distribution of this software is not allowed without
   -- express and prior written consent of the author.
   --
   -- THE SOFTWARE IS PROVIDED "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES,
   -- INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY
   -- AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL
   -- THE COPYRIGHT HOLDER OR DMSTEX BUSINESS SOLUTIONS LLC, ITS MEMBERS,
   -- MANAGERS, OR EMPLOYEES BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
   -- SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED
   -- TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
   -- PROFITS; CORRUPTION OF DATA, OR BUSINESS INTERRUPTION) HOWEVER CAUSED
   -- AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
   -- OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF
   -- THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH
   -- DAMAGE.
   --
   --


----------------------------------------
function describe
   return varchar2
is
begin
   return 'Disposition of a Player''s Card (varchar2(4), Upper Case)';
end describe;
----------------------------------------
function get_seq
      (value_in  in  varchar2)
   return number
is
begin
   case value_in
   when 'HREV' then return 1;
   when 'LREV' then return 2;
   when 'LPAS' then return 3;
   when 'HDED' then return 4;
   when 'LELT' then return 5;
   when 'LELP' then return 6;
   else return null;
   end case;
end get_seq;
----------------------------------------
function get_desc
      (value_in  in  varchar2)
   return varchar2
is
begin
   case value_in
   when 'HREV' then return '(Holding) Player REVEALED to me they have the card';
   when 'LREV' then return '(Lacking) Eliminated with other player REVEALED card.';
   when 'LPAS' then return '(Lacking) Player PASSED because they do not have the card';
   when 'HDED' then return '(Holding) One of 3 cards player revealed to another, but DEDUCED to be this card';
   when 'LELT' then return '(Lacking) One of 3 cards player revealed to another, but ELIMINATED as too many cards of TYPE';
   when 'LELP' then return '(Lacking) One of 3 cards player revealed to another, but ELIMINATED as too many cards for PLAYER';
   else return null;
   end case;
end get_desc;
----------------------------------------
function includes
      (value_in  in  varchar2)
   return boolean
is
begin
   case value_in
   when 'HREV' then return TRUE;
   when 'LREV' then return TRUE;
   when 'LPAS' then return TRUE;
   when 'HDED' then return TRUE;
   when 'LELT' then return TRUE;
   when 'LELP' then return TRUE;
   else return FALSE;
   end case;
end includes;
----------------------------------------
function table_recs
   return Dispositions_dtab
is
begin
   return Dispositions_dtab
          (Dispositions_dobj('HREV', 1, '(Holding) Player REVEALED to me they have the card')
          ,Dispositions_dobj('LREV', 2, '(Lacking) Eliminated with other player REVEALED card.')
          ,Dispositions_dobj('LPAS', 3, '(Lacking) Player PASSED because they do not have the card')
          ,Dispositions_dobj('HDED', 4, '(Holding) One of 3 cards player revealed to another, but DEDUCED to be this card')
          ,Dispositions_dobj('LELT', 5, '(Lacking) One of 3 cards player revealed to another, but ELIMINATED as too many cards of TYPE')
          ,Dispositions_dobj('LELP', 6, '(Lacking) One of 3 cards player revealed to another, but ELIMINATED as too many cards for PLAYER')
          );
end table_recs;
----------------------------------------

end Dispositions_dom;
/
select 'DISPOSITIONS_DOM' as "Package Body:"
 from  user_errors
 where name  = 'DISPOSITIONS_DOM'
  and  type  = 'PACKAGE BODY'
  and  rownum = 1
/
select '('||line||'/'||position||') '||text as error
 from  user_errors
 where name = 'DISPOSITIONS_DOM'
  and  type = 'PACKAGE BODY'
 order by sequence
/

CREATE type Flagged_dobj
is
   -- Flagged Domain Value Record Type
object
   (value        varchar2(1)
   ,seq          number
   ,description  varchar2(1000)
   )
/
select 'FLAGGED_DOBJ' as "Type:"
 from  user_errors
 where name  = 'FLAGGED_DOBJ'
  and  type  = 'TYPE'
  and  rownum = 1
/
select '('||line||'/'||position||') '||text as error
 from  user_errors
 where name = 'FLAGGED_DOBJ'
  and  type = 'TYPE'
 order by sequence
/

CREATE type Flagged_dtab
is
   -- Flagged Domain Value Table Type
table of Flagged_dobj
/
select 'FLAGGED_DTAB' as "Type:"
 from  user_errors
 where name  = 'FLAGGED_DTAB'
  and  type  = 'TYPE'
  and  rownum = 1
/
select '('||line||'/'||position||') '||text as error
 from  user_errors
 where name = 'FLAGGED_DTAB'
  and  type = 'TYPE'
 order by sequence
/

CREATE package Flagged_dom
is

   -- Package Flagged_Dom
   --    Domains and Domain Values

   -- Application: Clue Notes For Oracle
   -- Generated by DTGen (http://dmstex.com/services/dtgen)
   -- December  16, 2013  11:32:29 AM

   --
   --
   -- © Duane.Dieterich@DMSTEX.com 2013
   --
   -- All Rights Reserved
   --
   -- No part of this software may be reproduced, copied, modified or adapted,
   -- without the prior written consent of the author, unless otherwise
   -- indicated for stand-alone materials.
   --
   -- You may quote extracts from this software with attribution to
   -- Duane.Dieterich@DMSTEX.com
   --
   -- For any other mode of sharing, please contact Duane.Dieterich@DMSTEX.com.
   --
   -- Commercial use and distribution of this software is not allowed without
   -- express and prior written consent of the author.
   --
   -- THE SOFTWARE IS PROVIDED "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES,
   -- INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY
   -- AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL
   -- THE COPYRIGHT HOLDER OR DMSTEX BUSINESS SOLUTIONS LLC, ITS MEMBERS,
   -- MANAGERS, OR EMPLOYEES BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
   -- SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED
   -- TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
   -- PROFITS; CORRUPTION OF DATA, OR BUSINESS INTERRUPTION) HOWEVER CAUSED
   -- AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
   -- OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF
   -- THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH
   -- DAMAGE.
   --
   --


   -- An instance of the Table Type
   tab  Flagged_dtab;

   -- Domain Description
   function describe
      return varchar2;

   -- Domain Values Functions
   function get_seq
         (value_in  in  varchar2)
      return number;
   function get_desc
         (value_in  in  varchar2)
      return varchar2;
   function includes
         (value_in  in  varchar2)
      return boolean;
   -- select * from table(flagged_dom.table_recs);
   function table_recs
      return Flagged_dtab;

end Flagged_dom;
/
select 'FLAGGED_DOM' as "Package:"
 from  user_errors
 where name  = 'FLAGGED_DOM'
  and  type  = 'PACKAGE'
  and  rownum = 1
/
select '('||line||'/'||position||') '||text as error
 from  user_errors
 where name = 'FLAGGED_DOM'
  and  type = 'PACKAGE'
 order by sequence
/

CREATE package body Flagged_dom
is

   -- Package Body Flagged_Dom
   --    Domains and Domain Values

   -- Application: Clue Notes For Oracle
   -- Generated by DTGen (http://dmstex.com/services/dtgen)
   -- December  16, 2013  11:32:29 AM

   --
   --
   -- © Duane.Dieterich@DMSTEX.com 2013
   --
   -- All Rights Reserved
   --
   -- No part of this software may be reproduced, copied, modified or adapted,
   -- without the prior written consent of the author, unless otherwise
   -- indicated for stand-alone materials.
   --
   -- You may quote extracts from this software with attribution to
   -- Duane.Dieterich@DMSTEX.com
   --
   -- For any other mode of sharing, please contact Duane.Dieterich@DMSTEX.com.
   --
   -- Commercial use and distribution of this software is not allowed without
   -- express and prior written consent of the author.
   --
   -- THE SOFTWARE IS PROVIDED "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES,
   -- INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY
   -- AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL
   -- THE COPYRIGHT HOLDER OR DMSTEX BUSINESS SOLUTIONS LLC, ITS MEMBERS,
   -- MANAGERS, OR EMPLOYEES BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
   -- SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED
   -- TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
   -- PROFITS; CORRUPTION OF DATA, OR BUSINESS INTERRUPTION) HOWEVER CAUSED
   -- AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
   -- OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF
   -- THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH
   -- DAMAGE.
   --
   --


----------------------------------------
function describe
   return varchar2
is
begin
   return 'Flagged or Null (varchar2(1), Upper Case)';
end describe;
----------------------------------------
function get_seq
      (value_in  in  varchar2)
   return number
is
begin
   case value_in
   when 'X' then return 1;
   else return null;
   end case;
end get_seq;
----------------------------------------
function get_desc
      (value_in  in  varchar2)
   return varchar2
is
begin
   case value_in
   when 'X' then return 'Flagged, Marked, or otherwise Indicated';
   else return null;
   end case;
end get_desc;
----------------------------------------
function includes
      (value_in  in  varchar2)
   return boolean
is
begin
   case value_in
   when 'X' then return TRUE;
   else return FALSE;
   end case;
end includes;
----------------------------------------
function table_recs
   return Flagged_dtab
is
begin
   return Flagged_dtab
          (Flagged_dobj('X', 1, 'Flagged, Marked, or otherwise Indicated')
          );
end table_recs;
----------------------------------------

end Flagged_dom;
/
select 'FLAGGED_DOM' as "Package Body:"
 from  user_errors
 where name  = 'FLAGGED_DOM'
  and  type  = 'PACKAGE BODY'
  and  rownum = 1
/
select '('||line||'/'||position||') '||text as error
 from  user_errors
 where name = 'FLAGGED_DOM'
  and  type = 'PACKAGE BODY'
 order by sequence
/

CREATE type Resolutions_dobj
is
   -- Resolutions Domain Value Record Type
object
   (value        varchar2(3)
   ,seq          number
   ,description  varchar2(1000)
   )
/
select 'RESOLUTIONS_DOBJ' as "Type:"
 from  user_errors
 where name  = 'RESOLUTIONS_DOBJ'
  and  type  = 'TYPE'
  and  rownum = 1
/
select '('||line||'/'||position||') '||text as error
 from  user_errors
 where name = 'RESOLUTIONS_DOBJ'
  and  type = 'TYPE'
 order by sequence
/

CREATE type Resolutions_dtab
is
   -- Resolutions Domain Value Table Type
table of Resolutions_dobj
/
select 'RESOLUTIONS_DTAB' as "Type:"
 from  user_errors
 where name  = 'RESOLUTIONS_DTAB'
  and  type  = 'TYPE'
  and  rownum = 1
/
select '('||line||'/'||position||') '||text as error
 from  user_errors
 where name = 'RESOLUTIONS_DTAB'
  and  type = 'TYPE'
 order by sequence
/

CREATE package Resolutions_dom
is

   -- Package Resolutions_Dom
   --    Domains and Domain Values

   -- Application: Clue Notes For Oracle
   -- Generated by DTGen (http://dmstex.com/services/dtgen)
   -- December  16, 2013  11:32:29 AM

   --
   --
   -- © Duane.Dieterich@DMSTEX.com 2013
   --
   -- All Rights Reserved
   --
   -- No part of this software may be reproduced, copied, modified or adapted,
   -- without the prior written consent of the author, unless otherwise
   -- indicated for stand-alone materials.
   --
   -- You may quote extracts from this software with attribution to
   -- Duane.Dieterich@DMSTEX.com
   --
   -- For any other mode of sharing, please contact Duane.Dieterich@DMSTEX.com.
   --
   -- Commercial use and distribution of this software is not allowed without
   -- express and prior written consent of the author.
   --
   -- THE SOFTWARE IS PROVIDED "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES,
   -- INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY
   -- AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL
   -- THE COPYRIGHT HOLDER OR DMSTEX BUSINESS SOLUTIONS LLC, ITS MEMBERS,
   -- MANAGERS, OR EMPLOYEES BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
   -- SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED
   -- TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
   -- PROFITS; CORRUPTION OF DATA, OR BUSINESS INTERRUPTION) HOWEVER CAUSED
   -- AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
   -- OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF
   -- THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH
   -- DAMAGE.
   --
   --


   -- An instance of the Table Type
   tab  Resolutions_dtab;

   -- Domain Description
   function describe
      return varchar2;

   -- Domain Values Functions
   function get_seq
         (value_in  in  varchar2)
      return number;
   function get_desc
         (value_in  in  varchar2)
      return varchar2;
   function includes
         (value_in  in  varchar2)
      return boolean;
   -- select * from table(resolutions_dom.table_recs);
   function table_recs
      return Resolutions_dtab;

end Resolutions_dom;
/
select 'RESOLUTIONS_DOM' as "Package:"
 from  user_errors
 where name  = 'RESOLUTIONS_DOM'
  and  type  = 'PACKAGE'
  and  rownum = 1
/
select '('||line||'/'||position||') '||text as error
 from  user_errors
 where name = 'RESOLUTIONS_DOM'
  and  type = 'PACKAGE'
 order by sequence
/

CREATE package body Resolutions_dom
is

   -- Package Body Resolutions_Dom
   --    Domains and Domain Values

   -- Application: Clue Notes For Oracle
   -- Generated by DTGen (http://dmstex.com/services/dtgen)
   -- December  16, 2013  11:32:29 AM

   --
   --
   -- © Duane.Dieterich@DMSTEX.com 2013
   --
   -- All Rights Reserved
   --
   -- No part of this software may be reproduced, copied, modified or adapted,
   -- without the prior written consent of the author, unless otherwise
   -- indicated for stand-alone materials.
   --
   -- You may quote extracts from this software with attribution to
   -- Duane.Dieterich@DMSTEX.com
   --
   -- For any other mode of sharing, please contact Duane.Dieterich@DMSTEX.com.
   --
   -- Commercial use and distribution of this software is not allowed without
   -- express and prior written consent of the author.
   --
   -- THE SOFTWARE IS PROVIDED "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES,
   -- INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY
   -- AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL
   -- THE COPYRIGHT HOLDER OR DMSTEX BUSINESS SOLUTIONS LLC, ITS MEMBERS,
   -- MANAGERS, OR EMPLOYEES BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
   -- SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED
   -- TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
   -- PROFITS; CORRUPTION OF DATA, OR BUSINESS INTERRUPTION) HOWEVER CAUSED
   -- AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
   -- OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF
   -- THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH
   -- DAMAGE.
   --
   --


----------------------------------------
function describe
   return varchar2
is
begin
   return 'Resolution of a Player''s Suggestion (varchar2(3), Upper Case)';
end describe;
----------------------------------------
function get_seq
      (value_in  in  varchar2)
   return number
is
begin
   case value_in
   when 'NOT' then return 1;
   when 'REV' then return 2;
   when 'DED' then return 3;
   when 'UND' then return 4;
   else return null;
   end case;
end get_seq;
----------------------------------------
function get_desc
      (value_in  in  varchar2)
   return varchar2
is
begin
   case value_in
   when 'NOT' then return 'Not Resolved – Unknown which card the player holds';
   when 'REV' then return 'Resolved – Player revealed held card';
   when 'DED' then return 'Resolved – Player''s held card was found with deduction';
   when 'UND' then return 'UNDO – Action was undone (includes false Accusations)';
   else return null;
   end case;
end get_desc;
----------------------------------------
function includes
      (value_in  in  varchar2)
   return boolean
is
begin
   case value_in
   when 'NOT' then return TRUE;
   when 'REV' then return TRUE;
   when 'DED' then return TRUE;
   when 'UND' then return TRUE;
   else return FALSE;
   end case;
end includes;
----------------------------------------
function table_recs
   return Resolutions_dtab
is
begin
   return Resolutions_dtab
          (Resolutions_dobj('NOT', 1, 'Not Resolved – Unknown which card the player holds')
          ,Resolutions_dobj('REV', 2, 'Resolved – Player revealed held card')
          ,Resolutions_dobj('DED', 3, 'Resolved – Player''s held card was found with deduction')
          ,Resolutions_dobj('UND', 4, 'UNDO – Action was undone (includes false Accusations)')
          );
end table_recs;
----------------------------------------

end Resolutions_dom;
/
select 'RESOLUTIONS_DOM' as "Package Body:"
 from  user_errors
 where name  = 'RESOLUTIONS_DOM'
  and  type  = 'PACKAGE BODY'
  and  rownum = 1
/
select '('||line||'/'||position||') '||text as error
 from  user_errors
 where name = 'RESOLUTIONS_DOM'
  and  type = 'PACKAGE BODY'
 order by sequence
/

