OPTIONS (SKIP=1)
LOAD DATA
APPEND INTO TABLE "CLUE"."USERS_ACT"
FIELDS CSV WITH EMBEDDED
TRAILING NULLCOLS
   (ID                             FLOAT EXTERNAL
   ,NAME                           CHAR(320)
   )
