
--
--  ntclsrc Installation Script
--
--  Must be run as a SYSTEM User (DBA)
--
-- Command Line Parameters:
--   1 - INSTALL_SYSTEM_CONNECT: SYSTEM/password@TNSALIAS
--       i.e. pass the username and password for the SYSTEM user
--            and the TNSALIAS for the connection to the database.
--       The Data Load installation requires this connection information.
--

spool install_ntclsrc.log

define INSTALL_SYSTEM_CONNECT="&1."

-- Must Set SQLPREFIX away from "#" Oracle Change Data Capture packages
set sqlprefix "~"

-- Using "^P", CHR(16), DLE as an escape character
set escape OFF
set escape ""

----------------------------------------
--  Prepare for Install
@dbi.sql "./installation_prepare.sql" "" "&INSTALL_SYSTEM_CONNECT."

----------------------------------------
-- SEQUENCE Install

@dbi.sql "CLUE/ACTIONS_SEQ.seq" "CLUE" "&INSTALL_SYSTEM_CONNECT."
@dbi.sql "CLUE/ACTION_CARDS_SEQ.seq" "CLUE" "&INSTALL_SYSTEM_CONNECT."
@dbi.sql "CLUE/CARDS_SEQ.seq" "CLUE" "&INSTALL_SYSTEM_CONNECT."
@dbi.sql "CLUE/CARD_TYPES_SEQ.seq" "CLUE" "&INSTALL_SYSTEM_CONNECT."
@dbi.sql "CLUE/GAMES_SEQ.seq" "CLUE" "&INSTALL_SYSTEM_CONNECT."
@dbi.sql "CLUE/PCARD_ACTIONS_SEQ.seq" "CLUE" "&INSTALL_SYSTEM_CONNECT."
@dbi.sql "CLUE/PLAYERS_SEQ.seq" "CLUE" "&INSTALL_SYSTEM_CONNECT."
@dbi.sql "CLUE/USERS_SEQ.seq" "CLUE" "&INSTALL_SYSTEM_CONNECT."

----------------------------------------
-- TYPE Install

@dbi.sql "CLUE/ACCUSATION_VOBJ.tspec" "CLUE" "&INSTALL_SYSTEM_CONNECT."
@dbi.sql "CLUE/ACCUSATION_VTAB.tspec" "CLUE" "&INSTALL_SYSTEM_CONNECT."
@dbi.sql "CLUE/ACTIONS_VOBJ.tspec" "CLUE" "&INSTALL_SYSTEM_CONNECT."
@dbi.sql "CLUE/ACTIONS_VTAB.tspec" "CLUE" "&INSTALL_SYSTEM_CONNECT."
@dbi.sql "CLUE/ACTION_CARDS_VOBJ.tspec" "CLUE" "&INSTALL_SYSTEM_CONNECT."
@dbi.sql "CLUE/ACTION_CARDS_VTAB.tspec" "CLUE" "&INSTALL_SYSTEM_CONNECT."
@dbi.sql "CLUE/CARDS_VOBJ.tspec" "CLUE" "&INSTALL_SYSTEM_CONNECT."
@dbi.sql "CLUE/CARDS_VTAB.tspec" "CLUE" "&INSTALL_SYSTEM_CONNECT."
@dbi.sql "CLUE/CARD_TYPES_VOBJ.tspec" "CLUE" "&INSTALL_SYSTEM_CONNECT."
@dbi.sql "CLUE/CARD_TYPES_VTAB.tspec" "CLUE" "&INSTALL_SYSTEM_CONNECT."
@dbi.sql "CLUE/DISPOSITIONS_DOBJ.tspec" "CLUE" "&INSTALL_SYSTEM_CONNECT."
@dbi.sql "CLUE/DISPOSITIONS_DTAB.tspec" "CLUE" "&INSTALL_SYSTEM_CONNECT."
@dbi.sql "CLUE/FLAGGED_DOBJ.tspec" "CLUE" "&INSTALL_SYSTEM_CONNECT."
@dbi.sql "CLUE/FLAGGED_DTAB.tspec" "CLUE" "&INSTALL_SYSTEM_CONNECT."
@dbi.sql "CLUE/GAMES_VOBJ.tspec" "CLUE" "&INSTALL_SYSTEM_CONNECT."
@dbi.sql "CLUE/GAMES_VTAB.tspec" "CLUE" "&INSTALL_SYSTEM_CONNECT."
@dbi.sql "CLUE/PCARD_ACTIONS_VOBJ.tspec" "CLUE" "&INSTALL_SYSTEM_CONNECT."
@dbi.sql "CLUE/PCARD_ACTIONS_VTAB.tspec" "CLUE" "&INSTALL_SYSTEM_CONNECT."
@dbi.sql "CLUE/PLAYERS_VOBJ.tspec" "CLUE" "&INSTALL_SYSTEM_CONNECT."
@dbi.sql "CLUE/PLAYERS_VTAB.tspec" "CLUE" "&INSTALL_SYSTEM_CONNECT."
@dbi.sql "CLUE/RESOLUTIONS_DOBJ.tspec" "CLUE" "&INSTALL_SYSTEM_CONNECT."
@dbi.sql "CLUE/RESOLUTIONS_DTAB.tspec" "CLUE" "&INSTALL_SYSTEM_CONNECT."
@dbi.sql "CLUE/REVELATION_VOBJ.tspec" "CLUE" "&INSTALL_SYSTEM_CONNECT."
@dbi.sql "CLUE/REVELATION_VTAB.tspec" "CLUE" "&INSTALL_SYSTEM_CONNECT."
@dbi.sql "CLUE/SUGGESTION_VOBJ.tspec" "CLUE" "&INSTALL_SYSTEM_CONNECT."
@dbi.sql "CLUE/SUGGESTION_VTAB.tspec" "CLUE" "&INSTALL_SYSTEM_CONNECT."
@dbi.sql "CLUE/USERS_VOBJ.tspec" "CLUE" "&INSTALL_SYSTEM_CONNECT."
@dbi.sql "CLUE/USERS_VTAB.tspec" "CLUE" "&INSTALL_SYSTEM_CONNECT."

----------------------------------------
-- PACKAGE Install

@dbi.sql "CLUE/ACCUSATION_DML.pspec" "CLUE" "&INSTALL_SYSTEM_CONNECT."
@dbi.sql "CLUE/ACTIONS_DML.pspec" "CLUE" "&INSTALL_SYSTEM_CONNECT."
@dbi.sql "CLUE/ACTIONS_TAB.pspec" "CLUE" "&INSTALL_SYSTEM_CONNECT."
@dbi.sql "CLUE/ACTION_CARDS_DML.pspec" "CLUE" "&INSTALL_SYSTEM_CONNECT."
@dbi.sql "CLUE/ACTION_CARDS_TAB.pspec" "CLUE" "&INSTALL_SYSTEM_CONNECT."
@dbi.sql "CLUE/CARDS_DML.pspec" "CLUE" "&INSTALL_SYSTEM_CONNECT."
@dbi.sql "CLUE/CARDS_TAB.pspec" "CLUE" "&INSTALL_SYSTEM_CONNECT."
@dbi.sql "CLUE/CARD_TYPES_DML.pspec" "CLUE" "&INSTALL_SYSTEM_CONNECT."
@dbi.sql "CLUE/CARD_TYPES_TAB.pspec" "CLUE" "&INSTALL_SYSTEM_CONNECT."
@dbi.sql "CLUE/CLUE.pspec" "CLUE" "&INSTALL_SYSTEM_CONNECT."
@dbi.sql "CLUE/DISPOSITIONS_DOM.pspec" "CLUE" "&INSTALL_SYSTEM_CONNECT."
@dbi.sql "CLUE/FLAGGED_DOM.pspec" "CLUE" "&INSTALL_SYSTEM_CONNECT."
@dbi.sql "CLUE/GAMES_DML.pspec" "CLUE" "&INSTALL_SYSTEM_CONNECT."
@dbi.sql "CLUE/GAMES_TAB.pspec" "CLUE" "&INSTALL_SYSTEM_CONNECT."
@dbi.sql "CLUE/PCARD_ACTIONS_DML.pspec" "CLUE" "&INSTALL_SYSTEM_CONNECT."
@dbi.sql "CLUE/PCARD_ACTIONS_TAB.pspec" "CLUE" "&INSTALL_SYSTEM_CONNECT."
@dbi.sql "CLUE/PLAYERS_DML.pspec" "CLUE" "&INSTALL_SYSTEM_CONNECT."
@dbi.sql "CLUE/PLAYERS_TAB.pspec" "CLUE" "&INSTALL_SYSTEM_CONNECT."
@dbi.sql "CLUE/RESOLUTIONS_DOM.pspec" "CLUE" "&INSTALL_SYSTEM_CONNECT."
@dbi.sql "CLUE/REVELATION_DML.pspec" "CLUE" "&INSTALL_SYSTEM_CONNECT."
@dbi.sql "CLUE/SUGGESTION_DML.pspec" "CLUE" "&INSTALL_SYSTEM_CONNECT."
@dbi.sql "CLUE/USERS_DML.pspec" "CLUE" "&INSTALL_SYSTEM_CONNECT."
@dbi.sql "CLUE/USERS_TAB.pspec" "CLUE" "&INSTALL_SYSTEM_CONNECT."
@dbi.sql "CLUE/UTIL.pspec" "CLUE" "&INSTALL_SYSTEM_CONNECT."

----------------------------------------
-- TABLE Install

@dbi.sql "CLUE/ACTIONS.tab" "CLUE" "&INSTALL_SYSTEM_CONNECT."
@dbi.sql "CLUE/ACTION_CARDS.tab" "CLUE" "&INSTALL_SYSTEM_CONNECT."
@dbi.sql "CLUE/CARDS.tab" "CLUE" "&INSTALL_SYSTEM_CONNECT."
@dbi.sql "CLUE/CARD_TYPES.tab" "CLUE" "&INSTALL_SYSTEM_CONNECT."
@dbi.sql "CLUE/GAMES.tab" "CLUE" "&INSTALL_SYSTEM_CONNECT."
@dbi.sql "CLUE/PCARD_ACTIONS.tab" "CLUE" "&INSTALL_SYSTEM_CONNECT."
@dbi.sql "CLUE/PLAYERS.tab" "CLUE" "&INSTALL_SYSTEM_CONNECT."
@dbi.sql "CLUE/USERS.tab" "CLUE" "&INSTALL_SYSTEM_CONNECT."
@dbi.sql "CLUE/UTIL_LOG.tab" "CLUE" "&INSTALL_SYSTEM_CONNECT."
@dbi.sql "CLUE/UTIL_NVP.tab" "CLUE" "&INSTALL_SYSTEM_CONNECT."
@dbi.sql "CLUE/UTIL_TRC.tab" "CLUE" "&INSTALL_SYSTEM_CONNECT."

----------------------------------------
-- INDEX Install

@dbi.sql "CLUE/ACTIONS.tabind" "CLUE" "&INSTALL_SYSTEM_CONNECT."
@dbi.sql "CLUE/ACTION_CARDS.tabind" "CLUE" "&INSTALL_SYSTEM_CONNECT."
@dbi.sql "CLUE/CARDS.tabind" "CLUE" "&INSTALL_SYSTEM_CONNECT."
@dbi.sql "CLUE/PCARD_ACTIONS.tabind" "CLUE" "&INSTALL_SYSTEM_CONNECT."
@dbi.sql "CLUE/UTIL_LOG.tabind" "CLUE" "&INSTALL_SYSTEM_CONNECT."

----------------------------------------
-- VIEW Install

@dbi.sql "CLUE/ACCUSATION.vw" "CLUE" "&INSTALL_SYSTEM_CONNECT."
@dbi.sql "CLUE/ACCUSATION_ACT.vw" "CLUE" "&INSTALL_SYSTEM_CONNECT."
@dbi.sql "CLUE/ACTIONS_A.vw" "CLUE" "&INSTALL_SYSTEM_CONNECT."
@dbi.sql "CLUE/ACTIONS_ACT.vw" "CLUE" "&INSTALL_SYSTEM_CONNECT."
@dbi.sql "CLUE/ACTION_CARDS_ACT.vw" "CLUE" "&INSTALL_SYSTEM_CONNECT."
@dbi.sql "CLUE/CARDS_ACT.vw" "CLUE" "&INSTALL_SYSTEM_CONNECT."
@dbi.sql "CLUE/CARD_TYPES_ACT.vw" "CLUE" "&INSTALL_SYSTEM_CONNECT."
@dbi.sql "CLUE/GAMES_ACT.vw" "CLUE" "&INSTALL_SYSTEM_CONNECT."
@dbi.sql "CLUE/PCARD_ACTIONS_ACT.vw" "CLUE" "&INSTALL_SYSTEM_CONNECT."
@dbi.sql "CLUE/PLAYERS_ACT.vw" "CLUE" "&INSTALL_SYSTEM_CONNECT."
@dbi.sql "CLUE/REVELATION.vw" "CLUE" "&INSTALL_SYSTEM_CONNECT."
@dbi.sql "CLUE/REVELATION_ACT.vw" "CLUE" "&INSTALL_SYSTEM_CONNECT."
@dbi.sql "CLUE/SUGGESTION.vw" "CLUE" "&INSTALL_SYSTEM_CONNECT."
@dbi.sql "CLUE/SUGGESTION_ACT.vw" "CLUE" "&INSTALL_SYSTEM_CONNECT."
@dbi.sql "CLUE/USERS_ACT.vw" "CLUE" "&INSTALL_SYSTEM_CONNECT."

----------------------------------------
-- PACKAGE BODY Install

@dbi.sql "CLUE/ACCUSATION_DML.pbody" "CLUE" "&INSTALL_SYSTEM_CONNECT."
@dbi.sql "CLUE/ACTIONS_DML.pbody" "CLUE" "&INSTALL_SYSTEM_CONNECT."
@dbi.sql "CLUE/ACTIONS_TAB.pbody" "CLUE" "&INSTALL_SYSTEM_CONNECT."
@dbi.sql "CLUE/ACTION_CARDS_DML.pbody" "CLUE" "&INSTALL_SYSTEM_CONNECT."
@dbi.sql "CLUE/ACTION_CARDS_TAB.pbody" "CLUE" "&INSTALL_SYSTEM_CONNECT."
@dbi.sql "CLUE/CARDS_DML.pbody" "CLUE" "&INSTALL_SYSTEM_CONNECT."
@dbi.sql "CLUE/CARDS_TAB.pbody" "CLUE" "&INSTALL_SYSTEM_CONNECT."
@dbi.sql "CLUE/CARD_TYPES_DML.pbody" "CLUE" "&INSTALL_SYSTEM_CONNECT."
@dbi.sql "CLUE/CARD_TYPES_TAB.pbody" "CLUE" "&INSTALL_SYSTEM_CONNECT."
@dbi.sql "CLUE/CLUE.pbody" "CLUE" "&INSTALL_SYSTEM_CONNECT."
@dbi.sql "CLUE/DISPOSITIONS_DOM.pbody" "CLUE" "&INSTALL_SYSTEM_CONNECT."
@dbi.sql "CLUE/FLAGGED_DOM.pbody" "CLUE" "&INSTALL_SYSTEM_CONNECT."
@dbi.sql "CLUE/GAMES_DML.pbody" "CLUE" "&INSTALL_SYSTEM_CONNECT."
@dbi.sql "CLUE/GAMES_TAB.pbody" "CLUE" "&INSTALL_SYSTEM_CONNECT."
@dbi.sql "CLUE/PCARD_ACTIONS_DML.pbody" "CLUE" "&INSTALL_SYSTEM_CONNECT."
@dbi.sql "CLUE/PCARD_ACTIONS_TAB.pbody" "CLUE" "&INSTALL_SYSTEM_CONNECT."
@dbi.sql "CLUE/PLAYERS_DML.pbody" "CLUE" "&INSTALL_SYSTEM_CONNECT."
@dbi.sql "CLUE/PLAYERS_TAB.pbody" "CLUE" "&INSTALL_SYSTEM_CONNECT."
@dbi.sql "CLUE/RESOLUTIONS_DOM.pbody" "CLUE" "&INSTALL_SYSTEM_CONNECT."
@dbi.sql "CLUE/REVELATION_DML.pbody" "CLUE" "&INSTALL_SYSTEM_CONNECT."
@dbi.sql "CLUE/SUGGESTION_DML.pbody" "CLUE" "&INSTALL_SYSTEM_CONNECT."
@dbi.sql "CLUE/USERS_DML.pbody" "CLUE" "&INSTALL_SYSTEM_CONNECT."
@dbi.sql "CLUE/USERS_TAB.pbody" "CLUE" "&INSTALL_SYSTEM_CONNECT."
@dbi.sql "CLUE/UTIL.pbody" "CLUE" "&INSTALL_SYSTEM_CONNECT."

----------------------------------------
-- TABLE_FOREIGN_KEY Install

@dbi.sql "CLUE/ACTIONS.tabfk" "CLUE" "&INSTALL_SYSTEM_CONNECT."
@dbi.sql "CLUE/ACTION_CARDS.tabfk" "CLUE" "&INSTALL_SYSTEM_CONNECT."
@dbi.sql "CLUE/CARDS.tabfk" "CLUE" "&INSTALL_SYSTEM_CONNECT."
@dbi.sql "CLUE/CARD_TYPES.tabfk" "CLUE" "&INSTALL_SYSTEM_CONNECT."
@dbi.sql "CLUE/GAMES.tabfk" "CLUE" "&INSTALL_SYSTEM_CONNECT."
@dbi.sql "CLUE/PCARD_ACTIONS.tabfk" "CLUE" "&INSTALL_SYSTEM_CONNECT."
@dbi.sql "CLUE/PLAYERS.tabfk" "CLUE" "&INSTALL_SYSTEM_CONNECT."

----------------------------------------
-- VIEW_FOREIGN_KEY Install

@dbi.sql "CLUE/ACCUSATION.vwfk" "CLUE" "&INSTALL_SYSTEM_CONNECT."
@dbi.sql "CLUE/ACCUSATION_ACT.vwfk" "CLUE" "&INSTALL_SYSTEM_CONNECT."
@dbi.sql "CLUE/ACTIONS_A.vwfk" "CLUE" "&INSTALL_SYSTEM_CONNECT."
@dbi.sql "CLUE/ACTIONS_ACT.vwfk" "CLUE" "&INSTALL_SYSTEM_CONNECT."
@dbi.sql "CLUE/ACTION_CARDS_ACT.vwfk" "CLUE" "&INSTALL_SYSTEM_CONNECT."
@dbi.sql "CLUE/CARDS_ACT.vwfk" "CLUE" "&INSTALL_SYSTEM_CONNECT."
@dbi.sql "CLUE/CARD_TYPES_ACT.vwfk" "CLUE" "&INSTALL_SYSTEM_CONNECT."
@dbi.sql "CLUE/GAMES_ACT.vwfk" "CLUE" "&INSTALL_SYSTEM_CONNECT."
@dbi.sql "CLUE/PCARD_ACTIONS_ACT.vwfk" "CLUE" "&INSTALL_SYSTEM_CONNECT."
@dbi.sql "CLUE/PLAYERS_ACT.vwfk" "CLUE" "&INSTALL_SYSTEM_CONNECT."
@dbi.sql "CLUE/REVELATION.vwfk" "CLUE" "&INSTALL_SYSTEM_CONNECT."
@dbi.sql "CLUE/REVELATION_ACT.vwfk" "CLUE" "&INSTALL_SYSTEM_CONNECT."
@dbi.sql "CLUE/SUGGESTION.vwfk" "CLUE" "&INSTALL_SYSTEM_CONNECT."
@dbi.sql "CLUE/SUGGESTION_ACT.vwfk" "CLUE" "&INSTALL_SYSTEM_CONNECT."

----------------------------------------
-- TRIGGER Install

@dbi.sql "CLUE/ACTIONS.tabtrg" "CLUE" "&INSTALL_SYSTEM_CONNECT."
@dbi.sql "CLUE/ACTION_CARDS.tabtrg" "CLUE" "&INSTALL_SYSTEM_CONNECT."
@dbi.sql "CLUE/CARDS.tabtrg" "CLUE" "&INSTALL_SYSTEM_CONNECT."
@dbi.sql "CLUE/CARD_TYPES.tabtrg" "CLUE" "&INSTALL_SYSTEM_CONNECT."
@dbi.sql "CLUE/GAMES.tabtrg" "CLUE" "&INSTALL_SYSTEM_CONNECT."
@dbi.sql "CLUE/PCARD_ACTIONS.tabtrg" "CLUE" "&INSTALL_SYSTEM_CONNECT."
@dbi.sql "CLUE/PLAYERS.tabtrg" "CLUE" "&INSTALL_SYSTEM_CONNECT."
@dbi.sql "CLUE/USERS.tabtrg" "CLUE" "&INSTALL_SYSTEM_CONNECT."

----------------------------------------
-- TRIGGER Install

@dbi.sql "CLUE/ACCUSATION.vwtrg" "CLUE" "&INSTALL_SYSTEM_CONNECT."
@dbi.sql "CLUE/ACCUSATION_ACT.vwtrg" "CLUE" "&INSTALL_SYSTEM_CONNECT."
@dbi.sql "CLUE/ACTIONS_A.vwtrg" "CLUE" "&INSTALL_SYSTEM_CONNECT."
@dbi.sql "CLUE/ACTIONS_ACT.vwtrg" "CLUE" "&INSTALL_SYSTEM_CONNECT."
@dbi.sql "CLUE/ACTION_CARDS_ACT.vwtrg" "CLUE" "&INSTALL_SYSTEM_CONNECT."
@dbi.sql "CLUE/CARDS_ACT.vwtrg" "CLUE" "&INSTALL_SYSTEM_CONNECT."
@dbi.sql "CLUE/CARD_TYPES_ACT.vwtrg" "CLUE" "&INSTALL_SYSTEM_CONNECT."
@dbi.sql "CLUE/GAMES_ACT.vwtrg" "CLUE" "&INSTALL_SYSTEM_CONNECT."
@dbi.sql "CLUE/PCARD_ACTIONS_ACT.vwtrg" "CLUE" "&INSTALL_SYSTEM_CONNECT."
@dbi.sql "CLUE/PLAYERS_ACT.vwtrg" "CLUE" "&INSTALL_SYSTEM_CONNECT."
@dbi.sql "CLUE/REVELATION.vwtrg" "CLUE" "&INSTALL_SYSTEM_CONNECT."
@dbi.sql "CLUE/REVELATION_ACT.vwtrg" "CLUE" "&INSTALL_SYSTEM_CONNECT."
@dbi.sql "CLUE/SUGGESTION.vwtrg" "CLUE" "&INSTALL_SYSTEM_CONNECT."
@dbi.sql "CLUE/SUGGESTION_ACT.vwtrg" "CLUE" "&INSTALL_SYSTEM_CONNECT."
@dbi.sql "CLUE/USERS_ACT.vwtrg" "CLUE" "&INSTALL_SYSTEM_CONNECT."

----------------------------------------
-- Finalize Installation (Includes SPOOL OFF)
@dbi.sql "./installation_finalize.sql" "" "&INSTALL_SYSTEM_CONNECT."

spool off

