
select '=== CLUE create_util_flow ===' as SCRIPT_NAME from dual;

-- Script File "create_util_flow"
--    Create APEX GUI Utilities using generated code

   -- Application: Clue Notes For Oracle
   -- Generated by DTGen (http://dmstex.com/services/dtgen)
   -- December  16, 2013  11:32:37 AM

   --
   --
   -- © Duane.Dieterich@DMSTEX.com 2013
   --
   -- All Rights Reserved
   --
   -- No part of this software may be reproduced, copied, modified or adapted,
   -- without the prior written consent of the author, unless otherwise
   -- indicated for stand-alone materials.
   --
   -- You may quote extracts from this software with attribution to
   -- Duane.Dieterich@DMSTEX.com
   --
   -- For any other mode of sharing, please contact Duane.Dieterich@DMSTEX.com.
   --
   -- Commercial use and distribution of this software is not allowed without
   -- express and prior written consent of the author.
   --
   -- THE SOFTWARE IS PROVIDED "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES,
   -- INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY
   -- AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL
   -- THE COPYRIGHT HOLDER OR DMSTEX BUSINESS SOLUTIONS LLC, ITS MEMBERS,
   -- MANAGERS, OR EMPLOYEES BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
   -- SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED
   -- TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
   -- PROFITS; CORRUPTION OF DATA, OR BUSINESS INTERRUPTION) HOWEVER CAUSED
   -- AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
   -- OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF
   -- THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH
   -- DAMAGE.
   --
   --



CREATE OR REPLACE package util_flow
is

   -- Package Util_Flow
   --    APEX GUI Utility settings and functions

   -- Application: Clue Notes For Oracle
   -- Generated by DTGen (http://dmstex.com/services/dtgen)
   -- December  16, 2013  11:32:37 AM

   --
   --
   -- © Duane.Dieterich@DMSTEX.com 2013
   --
   -- All Rights Reserved
   --
   -- No part of this software may be reproduced, copied, modified or adapted,
   -- without the prior written consent of the author, unless otherwise
   -- indicated for stand-alone materials.
   --
   -- You may quote extracts from this software with attribution to
   -- Duane.Dieterich@DMSTEX.com
   --
   -- For any other mode of sharing, please contact Duane.Dieterich@DMSTEX.com.
   --
   -- Commercial use and distribution of this software is not allowed without
   -- express and prior written consent of the author.
   --
   -- THE SOFTWARE IS PROVIDED "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES,
   -- INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY
   -- AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL
   -- THE COPYRIGHT HOLDER OR DMSTEX BUSINESS SOLUTIONS LLC, ITS MEMBERS,
   -- MANAGERS, OR EMPLOYEES BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
   -- SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED
   -- TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
   -- PROFITS; CORRUPTION OF DATA, OR BUSINESS INTERRUPTION) HOWEVER CAUSED
   -- AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
   -- OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF
   -- THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH
   -- DAMAGE.
   --
   --


   -- Note: Because this is expected to be the first load of these pages,
   --       "wwv_flow_api.g_id_offset" is not used.  IDs are queried from
   --       APEX and "wwv_flow_id.next_val" is used to create new IDs.

   -- To convert this from page generation to application generation,
   --   Templates like "wwv_flow_api.create_row_template" must be added
   --   to the export script, to include matching "p_id => 1283510651569179"
   --   references for every usage of the row_template in the export script.

   -- application/set_environment
   ------------------------------
   -- Schema (Database Table) Owner (wwv_flow_application_install.get_schema)
   sch_name   varchar2(30)  := 'DMSTEX';
   -- Workspace Name (apex_util.find_workspace (ws_id))
   ws_name    varchar2(30)  := 'DMSTEX';
   -- Application Name (wwv_flow_application_install.get_application_name)
   app_name   varchar2(30)  := 'NOTE1';
   -- Page OffSet from table.seq
   page_os    number        := 0;
   -- Workspace (Security Group) ID (wwv_flow_application_install.get_workspace_id)
   ws_id      number;
   -- Application (Flow) ID (wwv_flow_application_install.get_application_id)
   app_id     number;

   -- APEX Template Variables
   bb_tid     number;          -- (Button Type) Button Template ID
   bc_tid     number;          -- (Breadcrumb Type) Breadcrumb Template ID
   ilowh_tid  number;          -- (Item Label Type) Optional With Help Template ID
   lbl_tid    number;          -- (List Type) Button List Template ID
   rbr_tid    number;          -- (Region Type) Breadcrumb Region Template ID
   rfr_tid    number;          -- (Region Type) Form Region Template ID
   rlwi_tid   number;          -- (Region Type) List Region with Icon Template ID
   rrr_tid    number;          -- (Report Type) Report Region Template ID
   rsarc_tid  number;          -- (Report Type) Standard, Alternating Row Colors Template ID

   -- Shared Page and Component Export Variables
   bcp_id     number;          -- Breadcrumb Parent ID
   bcp2_id    number;          -- Secondary Breadcrumb Parent ID
   col_id     number;          -- Page Item Database Column ID
   event_id   number;          -- Dynamic Action Event ID
   irws_id    number;          -- Interactive Report Worksheet ID
   lst_id     number;          -- Navigation List ID
   lst_name   varchar2(32767); -- Navigation List Name
   lov_id     number;          -- List of Values ID
   mnu_id     number;          -- Navigation Menu ID
   mnu_name   varchar2(32767); -- Navigation Menu Name
   pname      varchar2(50);    -- Page Name
   pnum       number;          -- Page (Step) Number
   pprr_id    number;          -- Page Plug ID / Report Region ID
   sir_id     number;          -- Saved Interactive Report ID
   subb_id    number;          -- Submit Button ID
   subb2_id   number;          -- Secondary Submit Button ID
   tab_id     number;          -- UI Default Table ID
   ts_name    varchar2(30);    -- Tab Set Name

   -- Temporary Variables
   p          number;          -- Temporary Number
   s          varchar2(32767); -- Temporary String

   -- To show block numbers, modify this constant to TRUE
   show_block_bool  CONSTANT boolean := FALSE;
   procedure show_block
      (num_in  in  number);

   procedure init
      (install_type_in   in  varchar2 default 'UIDEF');

   procedure fin;

   function get_template_id
      (type_in      in varchar2
      ,class_in      in varchar2)
   return number;

   function get_lov_id
      (name_in  in  varchar2)
   return number;

   function get_list_id
      (name_in  in  varchar2)
   return number;

   function get_list_entry_id
      (lst_id_in  in  number
      ,text_in    in  varchar2)
   return number;

   function get_menu_id
      (name_in  in  varchar2)
   return number;

   function get_menu_option_id
      (mnu_id_in  in  number
      ,label_in   in  varchar2)
   return number;

   function get_fp_id
      (name_in  in  varchar2
      ,type_in  in  varchar2)
   return number;

end util_flow;
/
select 'UTIL_FLOW' as "Package:"
 from  user_errors
 where name  = 'UTIL_FLOW'
  and  type  = 'PACKAGE'
  and  rownum = 1
/
select '('||line||'/'||position||') '||text as error
 from  user_errors
 where name = 'UTIL_FLOW'
  and  type = 'PACKAGE'
 order by sequence
/

CREATE OR REPLACE package body util_flow
is

-- Package Body Util_Flow
--    Utility settings and functions

   -- Application: Clue Notes For Oracle
   -- Generated by DTGen (http://dmstex.com/services/dtgen)
   -- December  16, 2013  11:32:37 AM

   --
   --
   -- © Duane.Dieterich@DMSTEX.com 2013
   --
   -- All Rights Reserved
   --
   -- No part of this software may be reproduced, copied, modified or adapted,
   -- without the prior written consent of the author, unless otherwise
   -- indicated for stand-alone materials.
   --
   -- You may quote extracts from this software with attribution to
   -- Duane.Dieterich@DMSTEX.com
   --
   -- For any other mode of sharing, please contact Duane.Dieterich@DMSTEX.com.
   --
   -- Commercial use and distribution of this software is not allowed without
   -- express and prior written consent of the author.
   --
   -- THE SOFTWARE IS PROVIDED "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES,
   -- INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY
   -- AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL
   -- THE COPYRIGHT HOLDER OR DMSTEX BUSINESS SOLUTIONS LLC, ITS MEMBERS,
   -- MANAGERS, OR EMPLOYEES BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
   -- SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED
   -- TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
   -- PROFITS; CORRUPTION OF DATA, OR BUSINESS INTERRUPTION) HOWEVER CAUSED
   -- AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
   -- OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF
   -- THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH
   -- DAMAGE.
   --
   --


----------------------------------------
procedure show_block
      (num_in  in  number)
is
begin
   if show_block_bool then
      dbms_output.put_line('BLOCK #' || num_in || '#');
   end if;
end show_block;
----------------------------------------
procedure init
      (install_type_in   in  varchar2 default 'UIDEF')
is
begin
   -- Check install_type_in Value
   if install_type_in not in ('UIDEF', 'LOV', 'APP') then
      raise_application_error(-20000, 'init(), unknown type_in: ' || install_type_in);
   end if;
   -- Taken directly from a compilation of various APEX export files

   --       AAAA       PPPPP   EEEEEE  XX      XX
   --      AA  AA      PP  PP  EE       XX    XX
   --     AA    AA     PP  PP  EE        XX  XX
   --    AAAAAAAAAA    PPPPP   EEEE       XXXX
   --   AA        AA   PP      EE        XX  XX
   --  AA          AA  PP      EE       XX    XX
   --  AA          AA  PP      EEEEEE  XX      XX

   wwv_flow_application_install.set_schema(sch_name);
   ws_id := apex_util.find_security_group_id(ws_name);
   if install_type_in != 'UIDEF' then
      begin
         select application_id into app_id
          from  apex_applications
          where workspace        = ws_name
           and  application_name = app_name;
      exception when no_data_found then
         -- app_id := apex_util.minimum_free_application_id;
         raise_application_error(-20011, 'APEX: Unable to find Application ID' ||
               ' for application "' || app_name ||
                 '" in workspace "' || ws_name  || '"' );
      end;
      dbms_output.put_line('   APPLICATION ' || app_id || ' - ' || app_name);
   end if;
   if install_type_in = 'APP' then
      wwv_flow_application_install.set_workspace_id(ws_id);
      wwv_flow_application_install.set_application_id(app_id);
      wwv_flow_application_install.set_application_name(app_name);
   end if;
   dbms_output.put_line('  Set Credentials...');
   -- Assumes package is running as the Oracle user APEX_040000 or
   --   as the owner (parsing schema) of the application.
   wwv_flow_api.set_security_group_id(p_security_group_id => ws_id);

   -- Start of Import
   wwv_flow.g_import_in_progress := true;

   -- Set NLS
   select value into wwv_flow_api.g_nls_numeric_chars
    from nls_session_parameters
    where parameter='NLS_NUMERIC_CHARACTERS';
   execute immediate 'alter session set nls_numeric_characters=''.,''';
   wwv_flow.g_browser_language := 'en';

   dbms_output.put_line('  Check Compatibility...');
   -- This date identifies the minimum version required to import this file.
   wwv_flow_api.set_version(p_version_yyyy_mm_dd=>'2010.05.13');

   dbms_output.put_line('  Set Application ID...');
   wwv_flow.g_flow_id := app_id;

   if install_type_in != 'UIDEF' then
      -- Initialize and Error Check
      if ws_id is null then
         raise_application_error(-20012, 'APEX: ws_id is null.');
      end if;
      if ws_name is null then
         raise_application_error(-20012, 'APEX: ws_name is null.');
      end if;
      if app_id is null then
         raise_application_error(-20012, 'APEX: app_id is null.');
      end if;
      if app_name is null then
         raise_application_error(-20012, 'APEX: app_name is null.');
      end if;
   end if;

   if install_type_in = 'APP' then
      -- Set and Check APEX Template IDs
      bb_tid := get_template_id('Button','Button');
      if bb_tid is null then
         raise_application_error(-20012, 'APEX: bb_tid is null.');
      end if;
      bc_tid := get_template_id('Breadcrumb','Breadcrumb');
      if bc_tid is null then
         raise_application_error(-20012, 'APEX: bc_tid is null.');
      end if;
      ilowh_tid := get_template_id('Item Label','Optional Label with Help');
      if ilowh_tid is null then
         raise_application_error(-20012, 'APEX: ilowh_tid is null.');
      end if;
      lbl_tid := get_template_id('List','Button List');
      if lbl_tid is null then
         raise_application_error(-20012, 'APEX: lbl_tid is null.');
      end if;
      rbr_tid := get_template_id('Region','Breadcrumb Region');
      if rbr_tid is null then
         raise_application_error(-20012, 'APEX: rbr_tid is null.');
      end if;
      rfr_tid   := get_template_id('Region','Form Region');
      if rfr_tid is null then
         raise_application_error(-20012, 'APEX: rfr_tid is null.');
      end if;
      rlwi_tid := get_template_id('Region','List Region with Icon');
      if rlwi_tid is null then
         raise_application_error(-20012, 'APEX: rlwi_tid is null.');
      end if;
      rrr_tid := get_template_id('Region','Reports Region');
      if rrr_tid is null then
         raise_application_error(-20012, 'APEX: rrr_tid is null.');
      end if;
      rsarc_tid := get_template_id('Report','Standard, Alternating Row Colors');
      if rsarc_tid is null then
         raise_application_error(-20012, 'APEX: rsarc_tid is null.');
      end if;
   end if;
end init;
----------------------------------------
procedure fin
is
begin
   --application/end_environment
   commit;
   dbms_session.set_nls(param => 'NLS_NUMERIC_CHARACTERS'
                       ,value => '''' || replace(wwv_flow_api.g_nls_numeric_chars,'''','''''') || '''');
end fin;
----------------------------------------
function get_template_id
      (type_in      in varchar2
      ,class_in      in varchar2)
   return number
as
  retval  number;
begin
   --  min(template_id) selects one of the multiple region templates
   --                   for the "List Region with Icon" theme class
   --  NOTE: The min() group function will allow a null to be fetched
   --                  without throwing the "NO_DATA_FOUND" exception
   select min(template_id) into retval
    from  (select breadcrumb_template_id  template_id
            from  apex_application_temp_bc
            where application_id     = app_id
             and  workspace          = ws_name
             and  'Breadcrumb'       = type_in
             and  upper(theme_class) like upper(class_in)
           union all
           select button_template_id  template_id
            from  apex_application_temp_button
            where application_id     = app_id
             and  workspace          = ws_name
             and  'Button'           = type_in
             and  upper(theme_class) like upper(class_in)
           union all
           select calendar_template_id  template_id
            from  apex_application_temp_calendar
            where application_id     = app_id
             and  workspace          = ws_name
             and  'Calendar'         = type_in
             and  upper(theme_class) like upper(class_in)
           union all
           select label_template_id  template_id
            from  apex_application_temp_label
            where application_id     = app_id
             and  workspace          = ws_name
             and  'Item Label'       = type_in
             and  upper(theme_class) like upper(class_in)
           union all
           select list_template_id  template_id
            from  apex_application_temp_list
            where application_id     = app_id
             and  workspace          = ws_name
             and  'List'             = type_in
             and  upper(theme_class) like upper(class_in)
           union all
           select template_id  template_id
            from  apex_application_temp_page
            where application_id     = app_id
             and  workspace          = ws_name
             and  'Page'             = type_in
             and  upper(theme_class) like upper(class_in)
           union all
           select template_id  template_id
            from  apex_application_temp_popuplov
            where application_id         = app_id
             and  workspace              = ws_name
             and  'Popup List of Values' = type_in
             and  upper(theme_class) like upper(class_in)
           union all
           select region_template_id  template_id
            from  apex_application_temp_region
            where application_id     = app_id
             and  workspace          = ws_name
             and  'Region'           = type_in
             and  upper(theme_class) like upper(class_in)
           union all
           select template_id  template_id
            from  apex_application_temp_report
            where application_id     = app_id
             and  workspace          = ws_name
             and  'Report'           = type_in
             and  upper(theme_class) like upper(class_in)
           );
   if retval is null then
      raise_application_error(-20011, 'APEX: Unable to find ' || type_in ||
         ' template ' || class_in ||
         ' for application ' || app_name ||
         ' in workspace ' || ws_name );
   end if;
   return retval;
end get_template_id;
----------------------------------------
function get_lov_id
      (name_in  in  varchar2)
   return number
as
   retval  number;
begin
   select lov_id into retval
    from  apex_application_lovs
    where application_name    = app_name
     and  workspace           = ws_name
     --and  lov_type            = 'Dynamic'
     --and  lov_type            = 'Static'
     and  list_of_values_name = name_in;
   return retval;
exception when no_data_found then return null;
end get_lov_id;
----------------------------------------
function get_list_id
      (name_in  in  varchar2)
   return number
as
   retval  number;
begin
   select list_id into retval
    from  apex_application_lists
    where application_name = app_name
     and  workspace        = ws_name
     and  list_name        = name_in;
   return retval;
exception when no_data_found then return null;
end get_list_id;
----------------------------------------
function get_list_entry_id
      (lst_id_in  in  number
      ,text_in    in  varchar2)
   return number
as
   retval  number;
begin
   select list_entry_id into retval
    from  apex_application_list_entries
    where application_name = app_name
     and  workspace        = ws_name
     and  list_id          = lst_id_in
     and  entry_text       = text_in;
   return retval;
exception when no_data_found then return null;
end get_list_entry_id;
----------------------------------------
function get_menu_id
      (name_in  in  varchar2)
   return number
as
   retval  number;
begin
   select breadcrumb_id into retval
    from  apex_application_breadcrumbs
    where application_name = app_name
     and  workspace        = ws_name
     and  breadcrumb_name  = name_in;
   return retval;
exception when no_data_found then return null;
end get_menu_id;
----------------------------------------
function get_menu_option_id
      (mnu_id_in  in  number
      ,label_in   in  varchar2)
   return number
as
  retval  number;
begin
   select breadcrumb_entry_id into retval
    from  apex_application_bc_entries
    where application_name = app_name
     and  workspace        = ws_name
     and  breadcrumb_id    = mnu_id_in
     and  entry_label      = label_in;
   return retval;
exception when no_data_found then return null;
end get_menu_option_id;
----------------------------------------
function get_fp_id
      (name_in  in  varchar2
      ,type_in  in  varchar2)
   return number
as
   retval  number;
begin
   select application_process_id into retval
    from  apex_application_processes
    where application_name = app_name
     and  workspace        = ws_name
     and  process_type     = type_in
     and  process_name     = name_in;
   return retval;
exception when no_data_found then return null;
end get_fp_id;
----------------------------------------
end util_flow;
/
select 'UTIL_FLOW' as "Package Body:"
 from  user_errors
 where name  = 'UTIL_FLOW'
  and  type  = 'PACKAGE BODY'
  and  rownum = 1
/
select '('||line||'/'||position||') '||text as error
 from  user_errors
 where name = 'UTIL_FLOW'
  and  type = 'PACKAGE BODY'
 order by sequence
/

