
select '=== CLUE create_tab ===' as SCRIPT_NAME from dual;

-- Script File "create_tab"
--    Create Tables, Indexes, and Comments

   -- Application: Clue Notes For Oracle
   -- Generated by DTGen (http://dmstex.com/services/dtgen)
   -- December  16, 2013  11:32:28 AM

   --
   --
   -- © Duane.Dieterich@DMSTEX.com 2013
   --
   -- All Rights Reserved
   --
   -- No part of this software may be reproduced, copied, modified or adapted,
   -- without the prior written consent of the author, unless otherwise
   -- indicated for stand-alone materials.
   --
   -- You may quote extracts from this software with attribution to
   -- Duane.Dieterich@DMSTEX.com
   --
   -- For any other mode of sharing, please contact Duane.Dieterich@DMSTEX.com.
   --
   -- Commercial use and distribution of this software is not allowed without
   -- express and prior written consent of the author.
   --
   -- THE SOFTWARE IS PROVIDED "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES,
   -- INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY
   -- AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL
   -- THE COPYRIGHT HOLDER OR DMSTEX BUSINESS SOLUTIONS LLC, ITS MEMBERS,
   -- MANAGERS, OR EMPLOYEES BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
   -- SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED
   -- TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
   -- PROFITS; CORRUPTION OF DATA, OR BUSINESS INTERRUPTION) HOWEVER CAUSED
   -- AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
   -- OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF
   -- THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH
   -- DAMAGE.
   --
   --




begin
   dbms_output.put_line('----------------------------------------');
   dbms_output.put_line('Creating Table users');
end;
/
create sequence users_seq
/

create table users
   (id   NUMBER(38)
   ,name   VARCHAR2(320)
         constraint users_nn2 not null
   ) pctfree 5
/

comment on table users is 'Registered Users'
/

comment on column users.id is 'Surrogate Primary Key for these users'
/
comment on column users.name is 'Clue Notes User Name'
/

alter table users add constraint users_pk
   primary key (id)
/

begin
   dbms_output.put_line('----------------------------------------');
   dbms_output.put_line('Creating ACTIVE Indexes for users');
end;
/
alter table users add constraint users_nk
    unique (name
           )
/


--  NOTE: These Indexes are not tested in the UNIT TESTs
-- create index users_ia1 on users(aud_beg_usr)
-- /
-- create index users_ia2 on users(aud_beg_dtm)
-- /


begin
   dbms_output.put_line('----------------------------------------');
   dbms_output.put_line('Creating Table card_types');
end;
/
create sequence card_types_seq
/

create table card_types
   (id   NUMBER(38)
   ,user_id   NUMBER(38)
         constraint card_types_nn2 not null
   ,name   VARCHAR2(15)
         constraint card_types_nn3 not null
   ,sort_ord   NUMBER(2)
   ) pctfree 7
/

comment on table card_types is 'Players for each User''s Game'
/

comment on column card_types.id is 'Surrogate Primary Key for these card_types'
/
comment on column card_types.user_id is 'User for this Card Type'
/
comment on column card_types.name is 'Card Type Name'
/
comment on column card_types.sort_ord is 'Sort Order for Card Types'
/

alter table card_types add constraint card_types_pk
   primary key (id)
/

begin
   dbms_output.put_line('----------------------------------------');
   dbms_output.put_line('Creating ACTIVE Indexes for card_types');
end;
/
alter table card_types add constraint card_types_nk
    unique (user_id
           ,name
           )
/
--  Skipping duplicate FK index on card_types_nk1
--


--  NOTE: These Indexes are not tested in the UNIT TESTs
-- create index card_types_ia1 on card_types(aud_beg_usr)
-- /
-- create index card_types_ia2 on card_types(aud_beg_dtm)
-- /


begin
   dbms_output.put_line('----------------------------------------');
   dbms_output.put_line('Creating Table games');
end;
/
create sequence games_seq
/

create table games
   (id   NUMBER(38)
   ,user_id   NUMBER(38)
         constraint games_nn2 not null
   ,name   VARCHAR2(320)
         constraint games_nn3 not null
   ,last_act_num   NUMBER(2)
         constraint games_nn4 not null
   ,completed   VARCHAR2(1)
   ,hide_undo   VARCHAR2(1)
   ,hide_accuse   VARCHAR2(1)
   ,hide_missing   VARCHAR2(1)
   ,hide_my_sugg   VARCHAR2(1)
   ,hide_pcards   VARCHAR2(1)
   ,hide_sugg_hist   VARCHAR2(1)
   ) pctfree 10
/

comment on table games is 'Individual User''s Games'
/

comment on column games.id is 'Surrogate Primary Key for these games'
/
comment on column games.user_id is 'User for this Game'
/
comment on column games.name is 'User''s Game Name'
/
comment on column games.last_act_num is 'Number of Last Actions to Display in User''s Game'
/
comment on column games.completed is 'Flag indicating the Game is complete'
/
comment on column games.hide_undo is 'Flag indicating to hide the Accusations Report in Users'' Game'
/
comment on column games.hide_accuse is 'Flag indicating to hide the Accusations Report in Users'' Game'
/
comment on column games.hide_missing is 'Flag indicating to hide the Missing Cards Report in Users'' Game'
/
comment on column games.hide_my_sugg is 'Flag indicating to hide the My Suggestions Report in Users'' Game'
/
comment on column games.hide_pcards is 'Flag indicating to hide the Player Cards Report in Users'' Game'
/
comment on column games.hide_sugg_hist is 'Flag indicating to hide the Suggestion History Report in Users'' Game'
/

alter table games add constraint games_pk
   primary key (id)
/

begin
   dbms_output.put_line('----------------------------------------');
   dbms_output.put_line('Creating ACTIVE Indexes for games');
end;
/
alter table games add constraint games_nk
    unique (user_id
           ,name
           )
/
--  Skipping duplicate FK index on games_nk1
--


--  NOTE: These Indexes are not tested in the UNIT TESTs
-- create index games_ia1 on games(aud_beg_usr)
-- /
-- create index games_ia2 on games(aud_beg_dtm)
-- /


begin
   dbms_output.put_line('----------------------------------------');
   dbms_output.put_line('Creating Table players');
end;
/
create sequence players_seq
/

create table players
   (id   NUMBER(38)
   ,game_id   NUMBER(38)
         constraint players_nn2 not null
   ,name   VARCHAR2(15)
         constraint players_nn3 not null
   ,seq   NUMBER(2)
         constraint players_nn4 not null
   ,total_cards   NUMBER(2)
   ) pctfree 7
/

comment on table players is 'Players for each User''s Game'
/

comment on column players.id is 'Surrogate Primary Key for these players'
/
comment on column players.game_id is 'User''s Game for this Player'
/
comment on column players.name is 'Player''s Name'
/
comment on column players.seq is 'Player''s Sequence from User in Game'
/
comment on column players.total_cards is 'Total Cards Held by Player'
/

alter table players add constraint players_pk
   primary key (id)
/

begin
   dbms_output.put_line('----------------------------------------');
   dbms_output.put_line('Creating ACTIVE Indexes for players');
end;
/
alter table players add constraint players_nk
    unique (game_id
           ,name
           )
/
alter table players add constraint players_ux1
    unique (game_id
           ,seq
           )
/
--  Skipping duplicate FK index on players_nk1
--


--  NOTE: These Indexes are not tested in the UNIT TESTs
-- create index players_ia1 on players(aud_beg_usr)
-- /
-- create index players_ia2 on players(aud_beg_dtm)
-- /


begin
   dbms_output.put_line('----------------------------------------');
   dbms_output.put_line('Creating Table cards');
end;
/
create sequence cards_seq
/

create table cards
   (id   NUMBER(38)
   ,game_id   NUMBER(38)
         constraint cards_nn2 not null
   ,name   VARCHAR2(15)
         constraint cards_nn3 not null
   ,ctype_id   NUMBER(38)
         constraint cards_nn4 not null
   ) pctfree 8
/

comment on table cards is 'Cards for each User''s Game'
/

comment on column cards.id is 'Surrogate Primary Key for these cards'
/
comment on column cards.game_id is 'User''s Game for this Card'
/
comment on column cards.name is 'Card Name'
/
comment on column cards.ctype_id is 'Card Type'
/

alter table cards add constraint cards_pk
   primary key (id)
/

begin
   dbms_output.put_line('----------------------------------------');
   dbms_output.put_line('Creating ACTIVE Indexes for cards');
end;
/
alter table cards add constraint cards_nk
    unique (game_id
           ,name
           )
/
--  Skipping duplicate FK index on cards_nk1
--
--  Skipping duplicate FK index on cardsix1
--
create index cards_ix1
    on cards
           (ctype_id
           ,game_id
           )
/


--  NOTE: These Indexes are not tested in the UNIT TESTs
-- create index cards_ia1 on cards(aud_beg_usr)
-- /
-- create index cards_ia2 on cards(aud_beg_dtm)
-- /


begin
   dbms_output.put_line('----------------------------------------');
   dbms_output.put_line('Creating Table actions');
end;
/
create sequence actions_seq
/

create table actions
   (id   NUMBER(38)
   ,actions_sub_type   VARCHAR2(25)
   ,player_id   NUMBER(38)
         constraint actions_nn3 not null
   ,seq   NUMBER(3)
         constraint actions_nn4 not null
   ,resolved   VARCHAR2(3)
         constraint actions_nn5 not null
   ,res_action_id   NUMBER(38)
   ,rev_player_id   NUMBER(38)
   ) cluster act_clus (id)
/

comment on table actions is 'Player''s Suggestions for each User''s Game'
/

comment on column actions.id is 'Surrogate Primary Key for these actions'
/
comment on column actions.actions_sub_type is 'Sub-type for these actions'
/
comment on column actions.player_id is 'Player that took this Action'
/
comment on column actions.seq is 'Sequence Number for this Action'
/
comment on column actions.resolved is 'Resolved Status for this Action'
/
comment on column actions.res_action_id is '(suggestion Sub-type) The current Action when this Suggestion was resolved'
/
comment on column actions.rev_player_id is '(suggestion Sub-type) Player that reveled a card for this Suggestion'
/

alter table actions add constraint actions_pk
   primary key (id)
/

begin
   dbms_output.put_line('----------------------------------------');
   dbms_output.put_line('Creating ACTIVE Indexes for actions');
end;
/
alter table actions add constraint actions_nk
    unique (player_id
           ,seq
           )
/
--  Skipping duplicate FK index on actions_nk1
--
create index actions_fx2 on actions(res_action_id)
/
create index actions_fx3 on actions(rev_player_id)
/
create index actions_ist on actions(actions_sub_type)
/
create index actions_ix1
    on actions
           (player_id
           ,resolved
           )
/


--  NOTE: These Indexes are not tested in the UNIT TESTs
-- create index actions_ia1 on actions(aud_beg_usr)
-- /
-- create index actions_ia2 on actions(aud_beg_dtm)
-- /


begin
   dbms_output.put_line('----------------------------------------');
   dbms_output.put_line('Creating Table action_cards');
end;
/
create sequence action_cards_seq
/

create table action_cards
   (id   NUMBER(38)
   ,action_id   NUMBER(38)
         constraint action_cards_nn2 not null
   ,card_id   NUMBER(38)
         constraint action_cards_nn3 not null
   ) cluster act_clus (action_id)
/

comment on table action_cards is 'Player''s Card Suggestions for each User''s Game'
/

comment on column action_cards.id is 'Surrogate Primary Key for these action_cards'
/
comment on column action_cards.action_id is 'Action for this Card'
/
comment on column action_cards.card_id is 'Card for this Action'
/

alter table action_cards add constraint action_cards_pk
   primary key (id)
/

begin
   dbms_output.put_line('----------------------------------------');
   dbms_output.put_line('Creating ACTIVE Indexes for action_cards');
end;
/
alter table action_cards add constraint action_cards_nk
    unique (action_id
           ,card_id
           )
/
--  Skipping duplicate FK index on action_cards_nk1
--
create index action_cards_fx2 on action_cards(card_id)
/


--  NOTE: These Indexes are not tested in the UNIT TESTs
-- create index action_cards_ia1 on action_cards(aud_beg_usr)
-- /
-- create index action_cards_ia2 on action_cards(aud_beg_dtm)
-- /


begin
   dbms_output.put_line('----------------------------------------');
   dbms_output.put_line('Creating Table pcard_actions');
end;
/
create sequence pcard_actions_seq
/

create table pcard_actions
   (id   NUMBER(38)
   ,card_id   NUMBER(38)
         constraint pcard_actions_nn2 not null
   ,disposition   VARCHAR2(4)
         constraint pcard_actions_nn3 not null
   ,player_id   NUMBER(38)
         constraint pcard_actions_nn4 not null
   ,action_id   NUMBER(38)
         constraint pcard_actions_nn5 not null
   ) pctfree 8
/

comment on table pcard_actions is 'Player''s Cards for each User''s Game'
/

comment on column pcard_actions.id is 'Surrogate Primary Key for these pcard_actions'
/
comment on column pcard_actions.card_id is 'Card for this Player'
/
comment on column pcard_actions.disposition is 'Disposition of this Player''s Card'
/
comment on column pcard_actions.player_id is 'Player for this Card'
/
comment on column pcard_actions.action_id is 'The current Action when this Player''s Card was dispositioned'
/

alter table pcard_actions add constraint pcard_actions_pk
   primary key (id)
/

begin
   dbms_output.put_line('----------------------------------------');
   dbms_output.put_line('Creating ACTIVE Indexes for pcard_actions');
end;
/
alter table pcard_actions add constraint pcard_actions_nk
    unique (card_id
           ,disposition
           ,player_id
           ,action_id
           )
/
--  Skipping duplicate FK index on pcard_actions_nk1
--
--  Skipping duplicate FK index on pcard_actionsix1
--
--  Skipping duplicate FK index on pcard_actionsix2
--
create index pcard_actions_ix1
    on pcard_actions
           (player_id
           ,disposition
           )
/
create index pcard_actions_ix2
    on pcard_actions
           (action_id
           ,disposition
           )
/


--  NOTE: These Indexes are not tested in the UNIT TESTs
-- create index pcard_actions_ia1 on pcard_actions(aud_beg_usr)
-- /
-- create index pcard_actions_ia2 on pcard_actions(aud_beg_dtm)
-- /

