
select '=== CLUE drop_usyn ===' as SCRIPT_NAME from dual;

-- Script File "drop_usyn"
--    Drop user synonyms

   -- Application: Clue Notes For Oracle
   -- Generated by DTGen (http://dmstex.com/services/dtgen)
   -- December  16, 2013  11:32:36 AM

   --
   --
   -- © Duane.Dieterich@DMSTEX.com 2013
   --
   -- All Rights Reserved
   --
   -- No part of this software may be reproduced, copied, modified or adapted,
   -- without the prior written consent of the author, unless otherwise
   -- indicated for stand-alone materials.
   --
   -- You may quote extracts from this software with attribution to
   -- Duane.Dieterich@DMSTEX.com
   --
   -- For any other mode of sharing, please contact Duane.Dieterich@DMSTEX.com.
   --
   -- Commercial use and distribution of this software is not allowed without
   -- express and prior written consent of the author.
   --
   -- THE SOFTWARE IS PROVIDED "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES,
   -- INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY
   -- AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL
   -- THE COPYRIGHT HOLDER OR DMSTEX BUSINESS SOLUTIONS LLC, ITS MEMBERS,
   -- MANAGERS, OR EMPLOYEES BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
   -- SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED
   -- TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
   -- PROFITS; CORRUPTION OF DATA, OR BUSINESS INTERRUPTION) HOWEVER CAUSED
   -- AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
   -- OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF
   -- THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH
   -- DAMAGE.
   --
   --



drop synonym Dispositions_DOBJ
/
drop synonym Dispositions_DOM
/
drop synonym Dispositions_DTAB
/
drop synonym Flagged_DOBJ
/
drop synonym Flagged_DOM
/
drop synonym Flagged_DTAB
/
drop synonym Resolutions_DOBJ
/
drop synonym Resolutions_DOM
/
drop synonym Resolutions_DTAB
/
drop synonym UTIL
/
drop synonym UTIL_LOG
/
drop synonym UTIL_NVP
/
drop synonym UTIL_TRC
/
drop synonym accusation
/
drop synonym accusation_ACT
/
drop synonym accusation_DML
/
drop synonym accusation_VOBJ
/
drop synonym accusation_VTAB
/
drop synonym action_cards
/
drop synonym action_cards_ACT
/
drop synonym action_cards_DML
/
drop synonym action_cards_SEQ
/
drop synonym action_cards_VOBJ
/
drop synonym action_cards_VTAB
/
drop synonym actions
/
drop synonym actions_A
/
drop synonym actions_ACT
/
drop synonym actions_DML
/
drop synonym actions_SEQ
/
drop synonym actions_VOBJ
/
drop synonym actions_VTAB
/
drop synonym card_types
/
drop synonym card_types_ACT
/
drop synonym card_types_DML
/
drop synonym card_types_SEQ
/
drop synonym card_types_VOBJ
/
drop synonym card_types_VTAB
/
drop synonym cards
/
drop synonym cards_ACT
/
drop synonym cards_DML
/
drop synonym cards_SEQ
/
drop synonym cards_VOBJ
/
drop synonym cards_VTAB
/
drop synonym clue
/
drop synonym games
/
drop synonym games_ACT
/
drop synonym games_DML
/
drop synonym games_SEQ
/
drop synonym games_VOBJ
/
drop synonym games_VTAB
/
drop synonym pcard_actions
/
drop synonym pcard_actions_ACT
/
drop synonym pcard_actions_DML
/
drop synonym pcard_actions_SEQ
/
drop synonym pcard_actions_VOBJ
/
drop synonym pcard_actions_VTAB
/
drop synonym players
/
drop synonym players_ACT
/
drop synonym players_DML
/
drop synonym players_SEQ
/
drop synonym players_VOBJ
/
drop synonym players_VTAB
/
drop synonym revelation
/
drop synonym revelation_ACT
/
drop synonym revelation_DML
/
drop synonym revelation_VOBJ
/
drop synonym revelation_VTAB
/
drop synonym suggestion
/
drop synonym suggestion_ACT
/
drop synonym suggestion_DML
/
drop synonym suggestion_VOBJ
/
drop synonym suggestion_VTAB
/
drop synonym users
/
drop synonym users_ACT
/
drop synonym users_DML
/
drop synonym users_SEQ
/
drop synonym users_VOBJ
/
drop synonym users_VTAB
/
