
select '=== CLUE drop_uidef ===' as SCRIPT_NAME from dual;

-- Script File "drop_uidef"
--    APEX export file used to drop User Interface Defaults

   -- Application: Clue Notes For Oracle
   -- Generated by DTGen (http://dmstex.com/services/dtgen)
   -- December  16, 2013  11:32:39 AM

   --
   --
   -- © Duane.Dieterich@DMSTEX.com 2013
   --
   -- All Rights Reserved
   --
   -- No part of this software may be reproduced, copied, modified or adapted,
   -- without the prior written consent of the author, unless otherwise
   -- indicated for stand-alone materials.
   --
   -- You may quote extracts from this software with attribution to
   -- Duane.Dieterich@DMSTEX.com
   --
   -- For any other mode of sharing, please contact Duane.Dieterich@DMSTEX.com.
   --
   -- Commercial use and distribution of this software is not allowed without
   -- express and prior written consent of the author.
   --
   -- THE SOFTWARE IS PROVIDED "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES,
   -- INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY
   -- AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL
   -- THE COPYRIGHT HOLDER OR DMSTEX BUSINESS SOLUTIONS LLC, ITS MEMBERS,
   -- MANAGERS, OR EMPLOYEES BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
   -- SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED
   -- TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
   -- PROFITS; CORRUPTION OF DATA, OR BUSINESS INTERRUPTION) HOWEVER CAUSED
   -- AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
   -- OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF
   -- THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH
   -- DAMAGE.
   --
   --


begin
   util_flow.init('UIDEF');
end;
/



begin

   -- Initialize and Error Check

   if util_flow.sch_name is null then
      raise_application_error(-20012, 'APEX: util_flow.sch_name is null.');
   end if;

   -- SET SCHEMA

   wwv_flow_hint.g_schema := util_flow.sch_name;
   wwv_flow_hint.check_schema_privs;

   --------------------------------------------------------------------
   dbms_output.put_line('SCHEMA ' || util_flow.sch_name ||
      ' - User Interface Defaults, Table users Defaults');
   --
   -- Import using sqlplus as the Oracle user: APEX_040000
   -- Created 11 Monday    December  16, 2013
   --

   wwv_flow_hint.remove_hint_priv(wwv_flow_hint.g_schema
                                 ,'USERS');

   wwv_flow_hint.remove_hint_priv(wwv_flow_hint.g_schema
                                 ,'USERS_ACT');


   ----------------------------------------

end;
/


begin

   -- Initialize and Error Check

   if util_flow.sch_name is null then
      raise_application_error(-20012, 'APEX: util_flow.sch_name is null.');
   end if;

   -- SET SCHEMA

   wwv_flow_hint.g_schema := util_flow.sch_name;
   wwv_flow_hint.check_schema_privs;

   --------------------------------------------------------------------
   dbms_output.put_line('SCHEMA ' || util_flow.sch_name ||
      ' - User Interface Defaults, Table card_types Defaults');
   --
   -- Import using sqlplus as the Oracle user: APEX_040000
   -- Created 11 Monday    December  16, 2013
   --

   wwv_flow_hint.remove_hint_priv(wwv_flow_hint.g_schema
                                 ,'CARD_TYPES');

   wwv_flow_hint.remove_hint_priv(wwv_flow_hint.g_schema
                                 ,'CARD_TYPES_ACT');


   ----------------------------------------

end;
/


begin

   -- Initialize and Error Check

   if util_flow.sch_name is null then
      raise_application_error(-20012, 'APEX: util_flow.sch_name is null.');
   end if;

   -- SET SCHEMA

   wwv_flow_hint.g_schema := util_flow.sch_name;
   wwv_flow_hint.check_schema_privs;

   --------------------------------------------------------------------
   dbms_output.put_line('SCHEMA ' || util_flow.sch_name ||
      ' - User Interface Defaults, Table games Defaults');
   --
   -- Import using sqlplus as the Oracle user: APEX_040000
   -- Created 11 Monday    December  16, 2013
   --

   wwv_flow_hint.remove_hint_priv(wwv_flow_hint.g_schema
                                 ,'GAMES');

   wwv_flow_hint.remove_hint_priv(wwv_flow_hint.g_schema
                                 ,'GAMES_ACT');


   ----------------------------------------

end;
/


begin

   -- Initialize and Error Check

   if util_flow.sch_name is null then
      raise_application_error(-20012, 'APEX: util_flow.sch_name is null.');
   end if;

   -- SET SCHEMA

   wwv_flow_hint.g_schema := util_flow.sch_name;
   wwv_flow_hint.check_schema_privs;

   --------------------------------------------------------------------
   dbms_output.put_line('SCHEMA ' || util_flow.sch_name ||
      ' - User Interface Defaults, Table players Defaults');
   --
   -- Import using sqlplus as the Oracle user: APEX_040000
   -- Created 11 Monday    December  16, 2013
   --

   wwv_flow_hint.remove_hint_priv(wwv_flow_hint.g_schema
                                 ,'PLAYERS');

   wwv_flow_hint.remove_hint_priv(wwv_flow_hint.g_schema
                                 ,'PLAYERS_ACT');


   ----------------------------------------

end;
/


begin

   -- Initialize and Error Check

   if util_flow.sch_name is null then
      raise_application_error(-20012, 'APEX: util_flow.sch_name is null.');
   end if;

   -- SET SCHEMA

   wwv_flow_hint.g_schema := util_flow.sch_name;
   wwv_flow_hint.check_schema_privs;

   --------------------------------------------------------------------
   dbms_output.put_line('SCHEMA ' || util_flow.sch_name ||
      ' - User Interface Defaults, Table cards Defaults');
   --
   -- Import using sqlplus as the Oracle user: APEX_040000
   -- Created 11 Monday    December  16, 2013
   --

   wwv_flow_hint.remove_hint_priv(wwv_flow_hint.g_schema
                                 ,'CARDS');

   wwv_flow_hint.remove_hint_priv(wwv_flow_hint.g_schema
                                 ,'CARDS_ACT');


   ----------------------------------------

end;
/


begin

   -- Initialize and Error Check

   if util_flow.sch_name is null then
      raise_application_error(-20012, 'APEX: util_flow.sch_name is null.');
   end if;

   -- SET SCHEMA

   wwv_flow_hint.g_schema := util_flow.sch_name;
   wwv_flow_hint.check_schema_privs;

   --------------------------------------------------------------------
   dbms_output.put_line('SCHEMA ' || util_flow.sch_name ||
      ' - User Interface Defaults, Table actions Defaults');
   --
   -- Import using sqlplus as the Oracle user: APEX_040000
   -- Created 11 Monday    December  16, 2013
   --

   wwv_flow_hint.remove_hint_priv(wwv_flow_hint.g_schema
                                 ,'ACTIONS');

   wwv_flow_hint.remove_hint_priv(wwv_flow_hint.g_schema
                                 ,'ACTIONS_ACT');


   ----------------------------------------

end;
/


begin

   -- Initialize and Error Check

   if util_flow.sch_name is null then
      raise_application_error(-20012, 'APEX: util_flow.sch_name is null.');
   end if;

   -- SET SCHEMA

   wwv_flow_hint.g_schema := util_flow.sch_name;
   wwv_flow_hint.check_schema_privs;

   --------------------------------------------------------------------
   dbms_output.put_line('SCHEMA ' || util_flow.sch_name ||
      ' - User Interface Defaults, Table accusation Defaults');
   --
   -- Import using sqlplus as the Oracle user: APEX_040000
   -- Created 11 Monday    December  16, 2013
   --

   wwv_flow_hint.remove_hint_priv(wwv_flow_hint.g_schema
                                 ,'ACCUSATION');

   wwv_flow_hint.remove_hint_priv(wwv_flow_hint.g_schema
                                 ,'ACCUSATION_ACT');


   ----------------------------------------

end;
/


begin

   -- Initialize and Error Check

   if util_flow.sch_name is null then
      raise_application_error(-20012, 'APEX: util_flow.sch_name is null.');
   end if;

   -- SET SCHEMA

   wwv_flow_hint.g_schema := util_flow.sch_name;
   wwv_flow_hint.check_schema_privs;

   --------------------------------------------------------------------
   dbms_output.put_line('SCHEMA ' || util_flow.sch_name ||
      ' - User Interface Defaults, Table revelation Defaults');
   --
   -- Import using sqlplus as the Oracle user: APEX_040000
   -- Created 11 Monday    December  16, 2013
   --

   wwv_flow_hint.remove_hint_priv(wwv_flow_hint.g_schema
                                 ,'REVELATION');

   wwv_flow_hint.remove_hint_priv(wwv_flow_hint.g_schema
                                 ,'REVELATION_ACT');


   ----------------------------------------

end;
/


begin

   -- Initialize and Error Check

   if util_flow.sch_name is null then
      raise_application_error(-20012, 'APEX: util_flow.sch_name is null.');
   end if;

   -- SET SCHEMA

   wwv_flow_hint.g_schema := util_flow.sch_name;
   wwv_flow_hint.check_schema_privs;

   --------------------------------------------------------------------
   dbms_output.put_line('SCHEMA ' || util_flow.sch_name ||
      ' - User Interface Defaults, Table suggestion Defaults');
   --
   -- Import using sqlplus as the Oracle user: APEX_040000
   -- Created 11 Monday    December  16, 2013
   --

   wwv_flow_hint.remove_hint_priv(wwv_flow_hint.g_schema
                                 ,'SUGGESTION');

   wwv_flow_hint.remove_hint_priv(wwv_flow_hint.g_schema
                                 ,'SUGGESTION_ACT');


   ----------------------------------------

end;
/


begin

   -- Initialize and Error Check

   if util_flow.sch_name is null then
      raise_application_error(-20012, 'APEX: util_flow.sch_name is null.');
   end if;

   -- SET SCHEMA

   wwv_flow_hint.g_schema := util_flow.sch_name;
   wwv_flow_hint.check_schema_privs;

   --------------------------------------------------------------------
   dbms_output.put_line('SCHEMA ' || util_flow.sch_name ||
      ' - User Interface Defaults, Table action_cards Defaults');
   --
   -- Import using sqlplus as the Oracle user: APEX_040000
   -- Created 11 Monday    December  16, 2013
   --

   wwv_flow_hint.remove_hint_priv(wwv_flow_hint.g_schema
                                 ,'ACTION_CARDS');

   wwv_flow_hint.remove_hint_priv(wwv_flow_hint.g_schema
                                 ,'ACTION_CARDS_ACT');


   ----------------------------------------

end;
/


begin

   -- Initialize and Error Check

   if util_flow.sch_name is null then
      raise_application_error(-20012, 'APEX: util_flow.sch_name is null.');
   end if;

   -- SET SCHEMA

   wwv_flow_hint.g_schema := util_flow.sch_name;
   wwv_flow_hint.check_schema_privs;

   --------------------------------------------------------------------
   dbms_output.put_line('SCHEMA ' || util_flow.sch_name ||
      ' - User Interface Defaults, Table pcard_actions Defaults');
   --
   -- Import using sqlplus as the Oracle user: APEX_040000
   -- Created 11 Monday    December  16, 2013
   --

   wwv_flow_hint.remove_hint_priv(wwv_flow_hint.g_schema
                                 ,'PCARD_ACTIONS');

   wwv_flow_hint.remove_hint_priv(wwv_flow_hint.g_schema
                                 ,'PCARD_ACTIONS_ACT');


   ----------------------------------------

end;
/

begin
   util_flow.fin;
end;
/

