
select '=== CLUE drop_view ===' as SCRIPT_NAME from dual;

-- Script File "drop_view"
--    Drop Active View and DML Package

   -- Application: Clue Notes For Oracle
   -- Generated by DTGen (http://dmstex.com/services/dtgen)
   -- December  16, 2013  11:32:36 AM

   --
   --
   -- © Duane.Dieterich@DMSTEX.com 2013
   --
   -- All Rights Reserved
   --
   -- No part of this software may be reproduced, copied, modified or adapted,
   -- without the prior written consent of the author, unless otherwise
   -- indicated for stand-alone materials.
   --
   -- You may quote extracts from this software with attribution to
   -- Duane.Dieterich@DMSTEX.com
   --
   -- For any other mode of sharing, please contact Duane.Dieterich@DMSTEX.com.
   --
   -- Commercial use and distribution of this software is not allowed without
   -- express and prior written consent of the author.
   --
   -- THE SOFTWARE IS PROVIDED "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES,
   -- INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY
   -- AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL
   -- THE COPYRIGHT HOLDER OR DMSTEX BUSINESS SOLUTIONS LLC, ITS MEMBERS,
   -- MANAGERS, OR EMPLOYEES BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
   -- SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED
   -- TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
   -- PROFITS; CORRUPTION OF DATA, OR BUSINESS INTERRUPTION) HOWEVER CAUSED
   -- AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
   -- OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF
   -- THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH
   -- DAMAGE.
   --
   --



drop package pcard_actions_dml
/
drop type pcard_actions_vtab
/
drop type pcard_actions_vobj
/
drop view pcard_actions_act
/

drop package action_cards_dml
/
drop type action_cards_vtab
/
drop type action_cards_vobj
/
drop view action_cards_act
/

drop package actions_dml
/
drop type actions_vtab
/
drop type actions_vobj
/
drop view actions_act
/
drop view actions_a
/

drop package cards_dml
/
drop type cards_vtab
/
drop type cards_vobj
/
drop view cards_act
/

drop package players_dml
/
drop type players_vtab
/
drop type players_vobj
/
drop view players_act
/

drop package games_dml
/
drop type games_vtab
/
drop type games_vobj
/
drop view games_act
/

drop package card_types_dml
/
drop type card_types_vtab
/
drop type card_types_vobj
/
drop view card_types_act
/

drop package users_dml
/
drop type users_vtab
/
drop type users_vobj
/
drop view users_act
/


