
select '=== CLUE drop_grnt ===' as SCRIPT_NAME from dual;

-- Script File "drop_grnt"
--    Revoke grants and audits on objects

   -- Application: Clue Notes For Oracle
   -- Generated by DTGen (http://dmstex.com/services/dtgen)
   -- December  16, 2013  11:32:36 AM

   --
   --
   -- © Duane.Dieterich@DMSTEX.com 2013
   --
   -- All Rights Reserved
   --
   -- No part of this software may be reproduced, copied, modified or adapted,
   -- without the prior written consent of the author, unless otherwise
   -- indicated for stand-alone materials.
   --
   -- You may quote extracts from this software with attribution to
   -- Duane.Dieterich@DMSTEX.com
   --
   -- For any other mode of sharing, please contact Duane.Dieterich@DMSTEX.com.
   --
   -- Commercial use and distribution of this software is not allowed without
   -- express and prior written consent of the author.
   --
   -- THE SOFTWARE IS PROVIDED "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES,
   -- INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY
   -- AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL
   -- THE COPYRIGHT HOLDER OR DMSTEX BUSINESS SOLUTIONS LLC, ITS MEMBERS,
   -- MANAGERS, OR EMPLOYEES BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
   -- SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED
   -- TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
   -- PROFITS; CORRUPTION OF DATA, OR BUSINESS INTERRUPTION) HOWEVER CAUSED
   -- AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
   -- OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF
   -- THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH
   -- DAMAGE.
   --
   --



--  Dispositions_DOBJ grants
revoke execute on Dispositions_DOBJ from CLUE_app
/

--  Dispositions_DOM grants
revoke execute on Dispositions_DOM from CLUE_app
/

--  Dispositions_DTAB grants
revoke execute on Dispositions_DTAB from CLUE_app
/

--  Flagged_DOBJ grants
revoke execute on Flagged_DOBJ from CLUE_app
/

--  Flagged_DOM grants
revoke execute on Flagged_DOM from CLUE_app
/

--  Flagged_DTAB grants
revoke execute on Flagged_DTAB from CLUE_app
/

--  Resolutions_DOBJ grants
revoke execute on Resolutions_DOBJ from CLUE_app
/

--  Resolutions_DOM grants
revoke execute on Resolutions_DOM from CLUE_app
/

--  Resolutions_DTAB grants
revoke execute on Resolutions_DTAB from CLUE_app
/

--  UTIL grants
revoke execute on UTIL from CLUE_app
/

--  UTIL_LOG grants
revoke delete on UTIL_LOG from CLUE_adm
/
revoke insert on UTIL_LOG from CLUE_app
/
revoke select on UTIL_LOG from CLUE_app
/

--  UTIL_NVP grants
revoke delete on UTIL_NVP from CLUE_adm
/
revoke insert on UTIL_NVP from CLUE_adm
/
revoke select on UTIL_NVP from CLUE_app
/
revoke update on UTIL_NVP from CLUE_adm
/

--  UTIL_TRC grants
revoke delete on UTIL_TRC from CLUE_app
/
revoke insert on UTIL_TRC from CLUE_app
/
revoke select on UTIL_TRC from CLUE_app
/
revoke update on UTIL_TRC from CLUE_app
/

--  accusation grants
revoke delete on accusation from CLUE_app
/
revoke insert on accusation from CLUE_app
/
revoke select on accusation from CLUE_app
/
revoke update on accusation from CLUE_app
/

--  accusation_ACT grants
revoke delete on accusation_ACT from CLUE_app
/
revoke insert on accusation_ACT from CLUE_app
/
revoke select on accusation_ACT from CLUE_app
/
revoke update on accusation_ACT from CLUE_app
/

--  accusation_DML grants
revoke execute on accusation_DML from CLUE_app
/

--  accusation_VOBJ grants
revoke execute on accusation_VOBJ from CLUE_app
/

--  accusation_VTAB grants
revoke execute on accusation_VTAB from CLUE_app
/

--  action_cards grants
revoke delete on action_cards from CLUE_app
/
revoke insert on action_cards from CLUE_app
/
revoke select on action_cards from CLUE_app
/
revoke update on action_cards from CLUE_app
/

--  action_cards_ACT grants
revoke delete on action_cards_ACT from CLUE_app
/
revoke insert on action_cards_ACT from CLUE_app
/
revoke select on action_cards_ACT from CLUE_app
/
revoke update on action_cards_ACT from CLUE_app
/

--  action_cards_DML grants
revoke execute on action_cards_DML from CLUE_app
/

--  action_cards_SEQ grants
revoke alter on action_cards_SEQ from CLUE_adm
/
revoke select on action_cards_SEQ from CLUE_app
/

--  action_cards_VOBJ grants
revoke execute on action_cards_VOBJ from CLUE_app
/

--  action_cards_VTAB grants
revoke execute on action_cards_VTAB from CLUE_app
/

--  actions grants
revoke delete on actions from CLUE_app
/
revoke insert on actions from CLUE_app
/
revoke select on actions from CLUE_app
/
revoke update on actions from CLUE_app
/

--  actions_A grants
revoke select on actions_A from CLUE_app
/

--  actions_ACT grants
revoke delete on actions_ACT from CLUE_app
/
revoke insert on actions_ACT from CLUE_app
/
revoke select on actions_ACT from CLUE_app
/
revoke update on actions_ACT from CLUE_app
/

--  actions_DML grants
revoke execute on actions_DML from CLUE_app
/

--  actions_SEQ grants
revoke alter on actions_SEQ from CLUE_adm
/
revoke select on actions_SEQ from CLUE_app
/

--  actions_VOBJ grants
revoke execute on actions_VOBJ from CLUE_app
/

--  actions_VTAB grants
revoke execute on actions_VTAB from CLUE_app
/

--  card_types grants
revoke delete on card_types from CLUE_app
/
revoke insert on card_types from CLUE_app
/
revoke select on card_types from CLUE_app
/
revoke update on card_types from CLUE_app
/

--  card_types_ACT grants
revoke delete on card_types_ACT from CLUE_app
/
revoke insert on card_types_ACT from CLUE_app
/
revoke select on card_types_ACT from CLUE_app
/
revoke update on card_types_ACT from CLUE_app
/

--  card_types_DML grants
revoke execute on card_types_DML from CLUE_app
/

--  card_types_SEQ grants
revoke alter on card_types_SEQ from CLUE_adm
/
revoke select on card_types_SEQ from CLUE_app
/

--  card_types_VOBJ grants
revoke execute on card_types_VOBJ from CLUE_app
/

--  card_types_VTAB grants
revoke execute on card_types_VTAB from CLUE_app
/

--  cards grants
revoke delete on cards from CLUE_app
/
revoke insert on cards from CLUE_app
/
revoke select on cards from CLUE_app
/
revoke update on cards from CLUE_app
/

--  cards_ACT grants
revoke delete on cards_ACT from CLUE_app
/
revoke insert on cards_ACT from CLUE_app
/
revoke select on cards_ACT from CLUE_app
/
revoke update on cards_ACT from CLUE_app
/

--  cards_DML grants
revoke execute on cards_DML from CLUE_app
/

--  cards_SEQ grants
revoke alter on cards_SEQ from CLUE_adm
/
revoke select on cards_SEQ from CLUE_app
/

--  cards_VOBJ grants
revoke execute on cards_VOBJ from CLUE_app
/

--  cards_VTAB grants
revoke execute on cards_VTAB from CLUE_app
/

--  clue grants
revoke execute on clue from CLUE_app
/

--  games grants
revoke delete on games from CLUE_app
/
revoke insert on games from CLUE_app
/
revoke select on games from CLUE_app
/
revoke update on games from CLUE_app
/

--  games_ACT grants
revoke delete on games_ACT from CLUE_app
/
revoke insert on games_ACT from CLUE_app
/
revoke select on games_ACT from CLUE_app
/
revoke update on games_ACT from CLUE_app
/

--  games_DML grants
revoke execute on games_DML from CLUE_app
/

--  games_SEQ grants
revoke alter on games_SEQ from CLUE_adm
/
revoke select on games_SEQ from CLUE_app
/

--  games_VOBJ grants
revoke execute on games_VOBJ from CLUE_app
/

--  games_VTAB grants
revoke execute on games_VTAB from CLUE_app
/

--  pcard_actions grants
revoke delete on pcard_actions from CLUE_app
/
revoke insert on pcard_actions from CLUE_app
/
revoke select on pcard_actions from CLUE_app
/
revoke update on pcard_actions from CLUE_app
/

--  pcard_actions_ACT grants
revoke delete on pcard_actions_ACT from CLUE_app
/
revoke insert on pcard_actions_ACT from CLUE_app
/
revoke select on pcard_actions_ACT from CLUE_app
/
revoke update on pcard_actions_ACT from CLUE_app
/

--  pcard_actions_DML grants
revoke execute on pcard_actions_DML from CLUE_app
/

--  pcard_actions_SEQ grants
revoke alter on pcard_actions_SEQ from CLUE_adm
/
revoke select on pcard_actions_SEQ from CLUE_app
/

--  pcard_actions_VOBJ grants
revoke execute on pcard_actions_VOBJ from CLUE_app
/

--  pcard_actions_VTAB grants
revoke execute on pcard_actions_VTAB from CLUE_app
/

--  players grants
revoke delete on players from CLUE_app
/
revoke insert on players from CLUE_app
/
revoke select on players from CLUE_app
/
revoke update on players from CLUE_app
/

--  players_ACT grants
revoke delete on players_ACT from CLUE_app
/
revoke insert on players_ACT from CLUE_app
/
revoke select on players_ACT from CLUE_app
/
revoke update on players_ACT from CLUE_app
/

--  players_DML grants
revoke execute on players_DML from CLUE_app
/

--  players_SEQ grants
revoke alter on players_SEQ from CLUE_adm
/
revoke select on players_SEQ from CLUE_app
/

--  players_VOBJ grants
revoke execute on players_VOBJ from CLUE_app
/

--  players_VTAB grants
revoke execute on players_VTAB from CLUE_app
/

--  revelation grants
revoke delete on revelation from CLUE_app
/
revoke insert on revelation from CLUE_app
/
revoke select on revelation from CLUE_app
/
revoke update on revelation from CLUE_app
/

--  revelation_ACT grants
revoke delete on revelation_ACT from CLUE_app
/
revoke insert on revelation_ACT from CLUE_app
/
revoke select on revelation_ACT from CLUE_app
/
revoke update on revelation_ACT from CLUE_app
/

--  revelation_DML grants
revoke execute on revelation_DML from CLUE_app
/

--  revelation_VOBJ grants
revoke execute on revelation_VOBJ from CLUE_app
/

--  revelation_VTAB grants
revoke execute on revelation_VTAB from CLUE_app
/

--  suggestion grants
revoke delete on suggestion from CLUE_app
/
revoke insert on suggestion from CLUE_app
/
revoke select on suggestion from CLUE_app
/
revoke update on suggestion from CLUE_app
/

--  suggestion_ACT grants
revoke delete on suggestion_ACT from CLUE_app
/
revoke insert on suggestion_ACT from CLUE_app
/
revoke select on suggestion_ACT from CLUE_app
/
revoke update on suggestion_ACT from CLUE_app
/

--  suggestion_DML grants
revoke execute on suggestion_DML from CLUE_app
/

--  suggestion_VOBJ grants
revoke execute on suggestion_VOBJ from CLUE_app
/

--  suggestion_VTAB grants
revoke execute on suggestion_VTAB from CLUE_app
/

--  users grants
revoke delete on users from CLUE_app
/
revoke insert on users from CLUE_app
/
revoke select on users from CLUE_app
/
revoke update on users from CLUE_app
/

--  users_ACT grants
revoke delete on users_ACT from CLUE_app
/
revoke insert on users_ACT from CLUE_app
/
revoke select on users_ACT from CLUE_app
/
revoke update on users_ACT from CLUE_app
/

--  users_DML grants
revoke execute on users_DML from CLUE_app
/

--  users_SEQ grants
revoke alter on users_SEQ from CLUE_adm
/
revoke select on users_SEQ from CLUE_app
/

--  users_VOBJ grants
revoke execute on users_VOBJ from CLUE_app
/

--  users_VTAB grants
revoke execute on users_VTAB from CLUE_app
/

